export const API_ERROR_CODES = [
  'VALIDATION_ERROR',
  'AUTH_REQUIRED',
  'AUTH_INVALID',
  'USER_DISABLED',
  'FORBIDDEN',
  'ORIGIN_FORBIDDEN',
  'PASSWORD_CHANGE_REQUIRED',
  'NOT_FOUND',
  'EXPORT_EXPIRED',
  'EXPORT_FILE_MISSING',
  'PAYLOAD_TOO_LARGE',
  'CONFLICT',
  'DELETE_RESTRICTED',
  'LAST_ADMIN',
  'BACKFILL_RUNNING',
  'TASK_OVERLAP',
  'SITE_CONFIG_CHANGED',
  'BASE_URL_PREFLIGHT_REQUIRED',
  'EXPORT_LIMIT_REACHED',
  'SITE_EXPORT_DISABLED',
  'SITE_INCOMPATIBLE',
  'SLO_CONFIG_FORBIDDEN',
  'UPSTREAM_USER_NOT_FOUND',
  'UPSTREAM_ADDRESS_FORBIDDEN',
  'LOGIN_RATE_LIMITED',
  'UPSTREAM_ERROR',
  'TOKEN_ROTATION_RESULT_UNKNOWN',
  'UPSTREAM_UNAVAILABLE',
  'INTERNAL_CONTRACT_ERROR',
  'INTERNAL_ERROR',
] as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[number]

export const MESSAGE_CODES = [
  'COLLECTION_RETRY_EXHAUSTED',
  'DATA_VALIDATION_MISMATCH',
  'UPSTREAM_RESPONSE_INVALID',
  'UPSTREAM_RESPONSE_TOO_LARGE',
  'SITE_CONFIG_CHANGED',
  'DEPENDENCY_WINDOWS_MISSING',
  'WORKER_LEASE_LOST',
  'EXPORT_DISK_LOW',
  'EXPORT_FILE_TOO_LARGE',
  'EXPORT_SNAPSHOT_FAILED',
  'EXPORT_WRITE_FAILED',
  'EXPORT_EXPIRED',
  'EXPORT_FILE_MISSING',
  'NOTIFICATION_DISABLED',
  'NOTIFICATION_NOT_CONFIGURED',
  'NOTIFICATION_TEST_SUCCEEDED',
  'DINGTALK_ADDRESS_FORBIDDEN',
  'DINGTALK_REJECTED',
  'DELIVERY_RETRY_EXHAUSTED',
  'DELIVERY_RETRY_SCHEDULED',
  'DATA_PENDING',
  'DATA_BACKFILLING',
  'DATA_WINDOW_MISSING',
  'DATA_UPSTREAM_UNAVAILABLE',
  'DATA_SCOPE_PAUSED',
  'DATA_PARTIAL_SITES',
  'DATA_VALIDATION_FAILED',
  'CAPABILITY_OK',
  'CAPABILITY_UPSTREAM_UNAVAILABLE',
  'CAPABILITY_RESPONSE_INVALID',
  'CAPABILITY_EXPORT_DISABLED',
  'CAPABILITY_IDENTITY_FAILED',
  'CAPABILITY_FIRST_USER_PROOF_FAILED',
  'CAPABILITY_NO_TRAFFIC_SKIPPED',
  'ALERT_SITE_OFFLINE',
  'ALERT_AUTH_EXPIRED',
  'ALERT_EXPORT_DISABLED',
  'ALERT_COLLECTION_MISSING',
  'ALERT_BACKFILL_FAILED',
  'ALERT_VALIDATION_FAILED',
  'ALERT_INSTANCE_STALE',
  'ALERT_INSTANCE_OFFLINE',
  'ALERT_NO_INSTANCE',
  'ALERT_CPU_HIGH',
  'ALERT_MEMORY_HIGH',
  'ALERT_DISK_HIGH',
  'ALERT_ACCOUNT_MISSING',
  'ALERT_ACCOUNT_IDENTITY_MISMATCH',
  'ALERT_ACCOUNT_DISABLED',
  'ALERT_ACCOUNT_QUOTA_EMPTY',
  'ALERT_CHANNEL_BALANCE_LOW',
  'ALERT_CHANNEL_RESPONSE_TIME_HIGH',
  'ALERT_CHANNEL_AVAILABILITY_LOW',
  'ALERT_SCOPE_INACTIVE',
  'SLO_USAGE_DELAY_TOO_HIGH',
  'SLO_USAGE_CONCURRENCY_TOO_LOW',
  'INTERNAL_CONTRACT_ERROR',
] as const

export type MessageCode = (typeof MESSAGE_CODES)[number]

const apiErrorCodeSet = new Set<string>(API_ERROR_CODES)
const messageCodeSet = new Set<string>(MESSAGE_CODES)
const stableI18nCodeSet = new Set<string>([
  ...API_ERROR_CODES,
  ...MESSAGE_CODES,
])

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === 'string' && apiErrorCodeSet.has(value)
}

export function isMessageCode(value: unknown): value is MessageCode {
  return typeof value === 'string' && messageCodeSet.has(value)
}

export function isStableI18nCode(value: unknown): value is string {
  return typeof value === 'string' && stableI18nCodeSet.has(value)
}

export const STABLE_I18N_CODES = [
  ...new Set<string>([...API_ERROR_CODES, ...MESSAGE_CODES]),
] as const
