CREATE TABLE IF NOT EXISTS schema_migration (
  version varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  checksum char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  applied_at bigint NOT NULL,
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schema_migration_progress (
  version varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  checksum char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  statement_index int NOT NULL DEFAULT '0',
  state varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ready',
  updated_at bigint NOT NULL,
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_user (
  id bigint NOT NULL AUTO_INCREMENT,
  username varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  password_hash varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  display_name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  role varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  status tinyint NOT NULL DEFAULT '1',
  must_change_password tinyint NOT NULL DEFAULT '0',
  session_version int NOT NULL DEFAULT '1',
  last_login_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_platform_user_username (username),
  KEY idx_platform_user_role_status (role,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  base_url varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  config_version int NOT NULL DEFAULT '1',
  remark varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  management_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  online_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unknown',
  auth_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unauthorized',
  statistics_status varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending_config',
  health_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unavailable',
  root_user_id bigint DEFAULT NULL,
  root_created_at bigint DEFAULT NULL,
  access_token_encrypted mediumtext COLLATE utf8mb4_unicode_ci,
  version varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  system_name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  quota_per_unit decimal(30,10) DEFAULT NULL,
  usd_exchange_rate decimal(30,10) DEFAULT NULL,
  last_rate_at bigint DEFAULT NULL,
  data_export_enabled tinyint NOT NULL DEFAULT '0',
  current_rpm bigint NOT NULL DEFAULT '0',
  current_tpm bigint NOT NULL DEFAULT '0',
  last_realtime_stat_at bigint DEFAULT NULL,
  probe_fail_count int NOT NULL DEFAULT '0',
  last_probe_at bigint DEFAULT NULL,
  last_probe_success_at bigint DEFAULT NULL,
  statistics_start_at bigint DEFAULT NULL,
  statistics_start_source varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  statistics_end_at bigint DEFAULT NULL,
  disabled_at bigint DEFAULT NULL,
  monitoring_start_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_base_url (base_url),
  KEY idx_site_status (management_status,online_status,auth_status),
  KEY idx_site_statistics_status (statistics_status,health_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_channel (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_channel_id bigint NOT NULL,
  name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  last_synced_at bigint NOT NULL,
  remote_missing tinyint NOT NULL DEFAULT '0',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_remote (site_id,remote_channel_id),
  KEY idx_site_channel_name (site_id,name),
  CONSTRAINT fk_site_channel_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_monitoring_pause (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  start_minute_ts bigint NOT NULL,
  end_minute_ts bigint DEFAULT NULL,
  reason varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'management_disabled',
  created_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_monitoring_pause (site_id,start_minute_ts),
  KEY idx_site_monitoring_pause_range (site_id,end_minute_ts,start_minute_ts),
  CONSTRAINT fk_site_monitoring_pause_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_capability (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  capability_key varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  message_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  message_params json DEFAULT NULL,
  checked_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_capability (site_id,capability_key),
  CONSTRAINT fk_site_capability_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  contact varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  remark varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  contract_amount decimal(38,10) NOT NULL DEFAULT '0.0000000000',
  payment_amount decimal(38,10) NOT NULL DEFAULT '0.0000000000',
  status varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'communicating',
  statistics_paused_at bigint DEFAULT NULL,
  statistics_backfill_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'none',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_customer_name (name),
  KEY idx_customer_status (status,updated_at),
  CONSTRAINT chk_customer_amounts_non_negative CHECK (((contract_amount >= 0) and (payment_amount >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS account (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  customer_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  remote_created_at bigint NOT NULL,
  username varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  display_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  remote_group varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  remote_status int NOT NULL DEFAULT '0',
  remote_state varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  remote_missing_count int NOT NULL DEFAULT '0',
  last_remote_seen_at bigint DEFAULT NULL,
  quota bigint NOT NULL DEFAULT '0',
  used_quota bigint NOT NULL DEFAULT '0',
  request_count bigint NOT NULL DEFAULT '0',
  managed_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  statistics_paused_at bigint DEFAULT NULL,
  statistics_backfill_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  last_synced_at bigint DEFAULT NULL,
  remark varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_site_remote_user (site_id,remote_user_id),
  KEY idx_account_customer_status (customer_id,managed_status),
  KEY idx_account_site_status (site_id,managed_status,remote_state),
  KEY idx_account_site_created (site_id,remote_created_at),
  KEY idx_account_remote_missing (site_id,remote_missing_count,last_remote_seen_at),
  KEY idx_account_username (username),
  CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_account_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_cursor (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  cursor_key varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'usage',
  last_complete_hour bigint DEFAULT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_cursor (site_id,cursor_key),
  CONSTRAINT fk_collection_cursor_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_run (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint DEFAULT NULL,
  site_config_version int NOT NULL DEFAULT '0',
  task_type varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  target_type varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'site',
  target_id bigint NOT NULL DEFAULT '0',
  trigger_type varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'schedule',
  start_timestamp bigint DEFAULT NULL,
  end_timestamp bigint DEFAULT NULL,
  scope json NOT NULL,
  active_key varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  fetched_rows bigint NOT NULL DEFAULT '0',
  written_rows bigint NOT NULL DEFAULT '0',
  retry_count int NOT NULL DEFAULT '0',
  priority int NOT NULL DEFAULT '0',
  next_attempt_at bigint NOT NULL,
  heartbeat_at bigint DEFAULT NULL,
  windows_initialized_at bigint DEFAULT NULL,
  total_windows int NOT NULL DEFAULT '0',
  completed_windows int NOT NULL DEFAULT '0',
  failed_windows int NOT NULL DEFAULT '0',
  created_request_id varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  last_request_id varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  error_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  error_params json DEFAULT NULL,
  error_message text COLLATE utf8mb4_unicode_ci,
  started_at bigint DEFAULT NULL,
  finished_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_run_active (active_key),
  KEY idx_collection_run_queue (status,next_attempt_at,priority,created_at),
  KEY idx_collection_run_materialize (windows_initialized_at,status,created_at),
  KEY idx_collection_run_site_range (site_id,task_type,start_timestamp),
  KEY idx_collection_run_target (target_type,target_id,created_at),
  CONSTRAINT fk_collection_run_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_window (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  attribution_status varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'attributed',
  fetched_rows bigint NOT NULL DEFAULT '0',
  source_hash char(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  last_fact_run_id bigint DEFAULT NULL,
  verified_at bigint DEFAULT NULL,
  last_error_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  last_error_params json DEFAULT NULL,
  last_error_message text COLLATE utf8mb4_unicode_ci,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_window (site_id,hour_ts),
  KEY idx_collection_window_status (status,hour_ts),
  KEY idx_collection_window_site_status (site_id,status,hour_ts),
  KEY fk_collection_window_run (last_fact_run_id),
  CONSTRAINT fk_collection_window_run FOREIGN KEY (last_fact_run_id) REFERENCES collection_run (id) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT fk_collection_window_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_collection_window_attribution_status CHECK ((attribution_status in (_utf8mb4'attributed',_utf8mb4'legacy_unattributed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_run_window (
  id bigint NOT NULL AUTO_INCREMENT,
  run_id bigint NOT NULL,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  attempt_count int NOT NULL DEFAULT '0',
  next_retry_at bigint DEFAULT NULL,
  fetched_rows bigint NOT NULL DEFAULT '0',
  written_rows bigint NOT NULL DEFAULT '0',
  error_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  error_params json DEFAULT NULL,
  error_message text COLLATE utf8mb4_unicode_ci,
  started_at bigint DEFAULT NULL,
  finished_at bigint DEFAULT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_run_window (run_id,site_id,hour_ts),
  KEY idx_collection_run_window_queue (run_id,status,next_retry_at,hour_ts),
  KEY idx_collection_run_window_site_hour (site_id,hour_ts,status),
  CONSTRAINT fk_collection_run_window_run FOREIGN KEY (run_id) REFERENCES collection_run (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_collection_run_window_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aggregation_bucket_lock (
  lock_key varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (lock_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usage_fact_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  username_snapshot varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  channel_id bigint NOT NULL DEFAULT '0',
  use_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  token_id bigint NOT NULL DEFAULT '0',
  token_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  collected_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_usage_fact_hourly (site_id,remote_user_id,model_name,channel_id,use_group,token_id,node_name,hour_ts),
  KEY idx_usage_fact_hourly_site_time (site_id,hour_ts),
  KEY idx_usage_fact_hourly_user_time (site_id,remote_user_id,hour_ts),
  KEY idx_usage_fact_hourly_model_time (site_id,model_name,hour_ts),
  KEY idx_usage_fact_hourly_channel_time (site_id,channel_id,hour_ts),
  KEY idx_usage_fact_hourly_time_user (hour_ts,site_id,remote_user_id),
  KEY idx_usage_fact_hourly_time_model_user (hour_ts,site_id,model_name,remote_user_id),
  KEY idx_usage_fact_hourly_time_channel_user (hour_ts,site_id,channel_id,remote_user_id),
  KEY idx_usage_fact_hourly_group_time (site_id,use_group,hour_ts),
  KEY idx_usage_fact_hourly_token_time (site_id,token_id,hour_ts),
  KEY idx_usage_fact_hourly_node_time (site_id,node_name,hour_ts),
  CONSTRAINT fk_usage_fact_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usage_fact_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  username_snapshot varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  channel_id bigint NOT NULL DEFAULT '0',
  use_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  token_id bigint NOT NULL DEFAULT '0',
  token_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_usage_fact_daily (site_id,remote_user_id,model_name,channel_id,use_group,token_id,node_name,date_key),
  KEY idx_usage_fact_daily_site_date (site_id,date_key),
  KEY idx_usage_fact_daily_user_date (site_id,remote_user_id,date_key),
  KEY idx_usage_fact_daily_model_date (site_id,model_name,date_key),
  KEY idx_usage_fact_daily_channel_date (site_id,channel_id,date_key),
  KEY idx_usage_fact_daily_group_date (site_id,use_group,date_key),
  KEY idx_usage_fact_daily_token_date (site_id,token_id,date_key),
  KEY idx_usage_fact_daily_node_date (site_id,node_name,date_key),
  CONSTRAINT fk_usage_fact_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS account_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  account_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_stat_hourly (account_id,hour_ts),
  KEY idx_account_stat_hourly_time (hour_ts,account_id),
  CONSTRAINT fk_account_stat_hourly_account FOREIGN KEY (account_id) REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS account_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  account_id bigint NOT NULL,
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_stat_daily (account_id,date_key),
  KEY idx_account_stat_daily_date (date_key,account_id),
  CONSTRAINT fk_account_stat_daily_account FOREIGN KEY (account_id) REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  customer_id bigint NOT NULL,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_stat_hourly (customer_id,site_id,hour_ts),
  KEY idx_customer_stat_hourly_time (site_id,hour_ts,customer_id),
  CONSTRAINT fk_customer_stat_hourly_customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_customer_stat_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  customer_id bigint NOT NULL,
  site_id bigint NOT NULL,
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_stat_daily (customer_id,site_id,date_key),
  KEY idx_customer_stat_daily_date (site_id,date_key,customer_id),
  CONSTRAINT fk_customer_stat_daily_customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_customer_stat_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_stat_hourly (site_id,hour_ts),
  KEY idx_site_stat_hourly_time (hour_ts,site_id),
  CONSTRAINT fk_site_stat_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_stat_daily (site_id,date_key),
  KEY idx_site_stat_daily_date (date_key,site_id),
  CONSTRAINT fk_site_stat_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS global_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_global_stat_hourly (hour_ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS global_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_global_stat_daily (date_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS model_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_model_stat_hourly (site_id,model_name,hour_ts),
  KEY idx_model_stat_hourly_time (site_id,hour_ts,model_name),
  CONSTRAINT fk_model_stat_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS model_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_model_stat_daily (site_id,model_name,date_key),
  KEY idx_model_stat_daily_date (site_id,date_key,model_name),
  CONSTRAINT fk_model_stat_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_stat_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  channel_id bigint NOT NULL DEFAULT '0',
  hour_ts bigint NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_stat_hourly (site_id,channel_id,hour_ts),
  KEY idx_channel_stat_hourly_time (site_id,hour_ts,channel_id),
  CONSTRAINT fk_channel_stat_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_stat_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  channel_id bigint NOT NULL DEFAULT '0',
  date_key int NOT NULL,
  request_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  token_used bigint NOT NULL DEFAULT '0',
  active_users bigint NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'complete',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_stat_daily (site_id,channel_id,date_key),
  KEY idx_channel_stat_daily_date (site_id,date_key,channel_id),
  CONSTRAINT fk_channel_stat_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_instance (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  hostname varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  is_master tinyint NOT NULL DEFAULT '0',
  runtime_version varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  goos varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  goarch varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  upstream_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unknown',
  upstream_stale_after_seconds int DEFAULT NULL,
  current_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unknown',
  first_seen_at bigint NOT NULL,
  started_at bigint DEFAULT NULL,
  last_seen_at bigint DEFAULT NULL,
  last_synced_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  retired_at bigint DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_instance_node (site_id,node_name),
  KEY idx_site_instance_status (site_id,current_status,last_seen_at),
  KEY idx_site_instance_active (site_id,retired_at,node_name),
  CONSTRAINT fk_site_instance_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_instance_status_minutely (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  minute_ts bigint NOT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  cpu_percent decimal(8,4) DEFAULT NULL,
  memory_percent decimal(8,4) DEFAULT NULL,
  disk_used_percent decimal(8,4) DEFAULT NULL,
  disk_total_bytes bigint DEFAULT NULL,
  disk_used_bytes bigint DEFAULT NULL,
  started_at bigint DEFAULT NULL,
  last_seen_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_instance_minutely (site_id,node_name,minute_ts),
  KEY idx_instance_minutely_time (site_id,minute_ts),
  CONSTRAINT fk_instance_minutely_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_instance_status_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  hour_ts bigint NOT NULL,
  cpu_max_percent decimal(8,4) DEFAULT NULL,
  cpu_avg_percent decimal(8,4) DEFAULT NULL,
  memory_max_percent decimal(8,4) DEFAULT NULL,
  memory_avg_percent decimal(8,4) DEFAULT NULL,
  disk_max_used_percent decimal(8,4) DEFAULT NULL,
  disk_last_used_percent decimal(8,4) DEFAULT NULL,
  online_samples int NOT NULL DEFAULT '0',
  abnormal_samples int NOT NULL DEFAULT '0',
  sample_count int NOT NULL DEFAULT '0',
  expected_sample_count int NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'missing',
  last_calculated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_instance_hourly (site_id,node_name,hour_ts),
  KEY idx_instance_hourly_time (site_id,hour_ts),
  CONSTRAINT fk_instance_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_instance_status_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  date_key int NOT NULL,
  cpu_max_percent decimal(8,4) DEFAULT NULL,
  cpu_avg_percent decimal(8,4) DEFAULT NULL,
  memory_max_percent decimal(8,4) DEFAULT NULL,
  memory_avg_percent decimal(8,4) DEFAULT NULL,
  disk_max_used_percent decimal(8,4) DEFAULT NULL,
  disk_last_used_percent decimal(8,4) DEFAULT NULL,
  online_samples int NOT NULL DEFAULT '0',
  abnormal_samples int NOT NULL DEFAULT '0',
  sample_count int NOT NULL DEFAULT '0',
  expected_sample_count int NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'missing',
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_instance_daily (site_id,node_name,date_key),
  KEY idx_instance_daily_date (site_id,date_key),
  CONSTRAINT fk_instance_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_status_minutely (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  minute_ts bigint NOT NULL,
  instance_count int NOT NULL DEFAULT '0',
  online_instance_count int NOT NULL DEFAULT '0',
  cpu_max_percent decimal(8,4) DEFAULT NULL,
  cpu_avg_percent decimal(8,4) DEFAULT NULL,
  memory_max_percent decimal(8,4) DEFAULT NULL,
  memory_avg_percent decimal(8,4) DEFAULT NULL,
  disk_max_used_percent decimal(8,4) DEFAULT NULL,
  health_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_minutely (site_id,minute_ts),
  KEY idx_site_minutely_time (minute_ts,site_id),
  CONSTRAINT fk_site_minutely_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_status_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  instance_count_max int NOT NULL DEFAULT '0',
  online_instance_count_min int NOT NULL DEFAULT '0',
  cpu_max_percent decimal(8,4) DEFAULT NULL,
  cpu_avg_percent decimal(8,4) DEFAULT NULL,
  memory_max_percent decimal(8,4) DEFAULT NULL,
  memory_avg_percent decimal(8,4) DEFAULT NULL,
  disk_max_used_percent decimal(8,4) DEFAULT NULL,
  abnormal_samples int NOT NULL DEFAULT '0',
  sample_count int NOT NULL DEFAULT '0',
  expected_sample_count int NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'missing',
  health_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  last_calculated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_status_hourly (site_id,hour_ts),
  KEY idx_site_status_hourly_time (hour_ts,site_id),
  CONSTRAINT fk_site_status_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_status_daily (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  date_key int NOT NULL,
  instance_count_max int NOT NULL DEFAULT '0',
  online_instance_count_min int NOT NULL DEFAULT '0',
  cpu_max_percent decimal(8,4) DEFAULT NULL,
  cpu_avg_percent decimal(8,4) DEFAULT NULL,
  memory_max_percent decimal(8,4) DEFAULT NULL,
  memory_avg_percent decimal(8,4) DEFAULT NULL,
  disk_max_used_percent decimal(8,4) DEFAULT NULL,
  abnormal_samples int NOT NULL DEFAULT '0',
  sample_count int NOT NULL DEFAULT '0',
  expected_sample_count int NOT NULL DEFAULT '0',
  data_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'missing',
  health_status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  is_final tinyint NOT NULL DEFAULT '0',
  last_calculated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_status_daily (site_id,date_key),
  KEY idx_site_status_daily_date (date_key,site_id),
  CONSTRAINT fk_site_status_daily_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alert_rule (
  id bigint NOT NULL AUTO_INCREMENT,
  rule_key varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  enabled tinyint NOT NULL DEFAULT '1',
  level varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  metric varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  compare_operator varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '>=',
  threshold_value decimal(30,10) DEFAULT NULL,
  for_times int NOT NULL DEFAULT '1',
  scope_type varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'global',
  scope_id bigint NOT NULL DEFAULT '0',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_rule_scope (rule_key,level,scope_type,scope_id),
  KEY idx_alert_rule_enabled (enabled,metric,scope_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alert_event (
  id bigint NOT NULL AUTO_INCREMENT,
  rule_id bigint NOT NULL,
  rule_key varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  site_id bigint DEFAULT NULL,
  target_type varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  target_key varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  active_key varchar(384) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  level varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  consecutive_count int NOT NULL DEFAULT '1',
  current_value decimal(30,10) DEFAULT NULL,
  threshold_value decimal(30,10) DEFAULT NULL,
  message_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  message_params json DEFAULT NULL,
  message varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  first_observed_at bigint NOT NULL,
  first_fired_at bigint DEFAULT NULL,
  last_fired_at bigint DEFAULT NULL,
  resolved_at bigint DEFAULT NULL,
  resolution_reason varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_event_active (active_key),
  KEY idx_alert_event_status_level (status,level,updated_at),
  KEY idx_alert_event_target (target_type,target_key,created_at),
  KEY idx_alert_event_site (site_id,status,updated_at),
  KEY fk_alert_event_rule (rule_id),
  CONSTRAINT fk_alert_event_rule FOREIGN KEY (rule_id) REFERENCES alert_rule (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_alert_event_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alert_delivery (
  id bigint NOT NULL AUTO_INCREMENT,
  alert_event_id bigint DEFAULT NULL,
  event_type varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  channel varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'dingtalk',
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  attempt_count int NOT NULL DEFAULT '0',
  claim_token varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  lease_expires_at bigint DEFAULT NULL,
  payload_snapshot json NOT NULL,
  error_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  response_code int DEFAULT NULL,
  response_message text COLLATE utf8mb4_unicode_ci,
  next_retry_at bigint DEFAULT NULL,
  sent_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_delivery_event (alert_event_id,event_type,channel),
  KEY idx_alert_delivery_retry (status,next_retry_at),
  KEY idx_alert_delivery_claim (status,lease_expires_at,next_retry_at,id),
  CONSTRAINT fk_alert_delivery_event FOREIGN KEY (alert_event_id) REFERENCES alert_event (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS export_job (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  format varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  statistics_type varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  filters json NOT NULL,
  filter_hash char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  active_key varchar(192) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  rate_snapshot json DEFAULT NULL,
  data_snapshot_at bigint DEFAULT NULL,
  status varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  progress int NOT NULL DEFAULT '0',
  attempt_count int NOT NULL DEFAULT '0',
  next_attempt_at bigint NOT NULL,
  heartbeat_at bigint DEFAULT NULL,
  claim_token varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  lease_expires_at bigint DEFAULT NULL,
  file_path varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  file_name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  file_size bigint NOT NULL DEFAULT '0',
  row_count bigint NOT NULL DEFAULT '0',
  error_code varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  error_params json DEFAULT NULL,
  error_message text COLLATE utf8mb4_unicode_ci,
  expires_at bigint DEFAULT NULL,
  started_at bigint DEFAULT NULL,
  finished_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_export_job_active (active_key),
  KEY idx_export_job_user (user_id,created_at),
  KEY idx_export_job_queue (status,next_attempt_at,created_at),
  KEY idx_export_job_expiry (status,expires_at),
  KEY idx_export_job_claim (status,lease_expires_at,next_attempt_at,id),
  CONSTRAINT fk_export_job_user FOREIGN KEY (user_id) REFERENCES platform_user (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_setting (
  id bigint NOT NULL AUTO_INCREMENT,
  setting_key varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  setting_value mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  value_type varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  is_secret tinyint NOT NULL DEFAULT '0',
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_platform_setting_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alert_evaluation_cursor (
  active_key varchar(384) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  last_sample_at bigint NOT NULL,
  last_sample_key varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (active_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS encryption_reencrypt_job (
  id bigint NOT NULL AUTO_INCREMENT,
  old_key_id char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  new_key_id char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  active_key varchar(16) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'staging',
  inventory_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  total_items bigint NOT NULL DEFAULT '0',
  staged_items bigint NOT NULL DEFAULT '0',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_encryption_reencrypt_active (active_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS encryption_reencrypt_item (
  job_id bigint NOT NULL,
  row_type varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  row_id bigint NOT NULL,
  aad_identity varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  new_ciphertext mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  needs_update tinyint NOT NULL DEFAULT '1',
  created_at bigint NOT NULL,
  PRIMARY KEY (job_id,row_type,row_id),
  KEY idx_encryption_reencrypt_item_job (job_id,row_type,row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS upstream_log_fact (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  config_version int NOT NULL,
  upstream_log_key char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  upstream_log_id bigint NOT NULL DEFAULT '0',
  created_at bigint NOT NULL,
  type int NOT NULL,
  remote_user_id bigint NOT NULL DEFAULT '0',
  username varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  token_id bigint NOT NULL DEFAULT '0',
  token_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  channel_id bigint NOT NULL DEFAULT '0',
  use_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  request_id varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  upstream_request_id varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  quota bigint NOT NULL DEFAULT '0',
  prompt_tokens bigint NOT NULL DEFAULT '0',
  completion_tokens bigint NOT NULL DEFAULT '0',
  use_time_seconds bigint NOT NULL DEFAULT '0',
  is_stream tinyint(1) NOT NULL DEFAULT '0',
  content_redacted varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  ip varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  collected_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_upstream_log_fact_site_key (site_id,config_version,upstream_log_key),
  KEY idx_upstream_log_fact_site_time (site_id,created_at,id),
  KEY idx_upstream_log_fact_type_time (type,created_at,id),
  KEY idx_upstream_log_fact_user_time (site_id,remote_user_id,created_at),
  KEY idx_upstream_log_fact_model_time (site_id,model_name,created_at),
  KEY idx_upstream_log_fact_token_time (site_id,token_id,created_at),
  KEY idx_upstream_log_fact_channel_time (site_id,channel_id,created_at),
  KEY idx_upstream_log_fact_group_time (site_id,use_group,created_at),
  KEY idx_upstream_log_fact_request (site_id,request_id),
  KEY idx_upstream_log_fact_upstream_request (site_id,upstream_request_id),
  CONSTRAINT fk_upstream_log_fact_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS upstream_log_collection_state (
  site_id bigint NOT NULL,
  config_version int NOT NULL,
  status varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  window_start bigint NOT NULL,
  window_end bigint NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  last_error_params json DEFAULT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  KEY idx_upstream_log_collection_state_status (status,updated_at),
  CONSTRAINT fk_upstream_log_collection_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_upstream_log_collection_state_status CHECK ((status in (_utf8mb4'pending',_utf8mb4'complete',_utf8mb4'partial',_utf8mb4'unavailable',_utf8mb4'disabled'))),
  CONSTRAINT chk_upstream_log_collection_state_window CHECK (((window_start >= 0) and (window_end >= window_start)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_user_inventory (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  remote_created_at bigint NOT NULL,
  username varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  display_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_role int NOT NULL,
  remote_status int NOT NULL,
  remote_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  quota bigint NOT NULL DEFAULT '0',
  used_quota bigint NOT NULL DEFAULT '0',
  request_count bigint NOT NULL DEFAULT '0',
  last_login_at bigint NOT NULL DEFAULT '0',
  remote_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_user_inventory_site_remote (site_id,remote_user_id),
  KEY idx_site_user_inventory_site_state (site_id,remote_state,remote_user_id),
  KEY idx_site_user_inventory_site_role (site_id,remote_role,remote_user_id),
  KEY idx_site_user_inventory_site_status (site_id,remote_status,remote_user_id),
  KEY idx_site_user_inventory_site_group (site_id,remote_group,remote_user_id),
  KEY idx_site_user_inventory_site_login (site_id,last_login_at,remote_user_id),
  KEY idx_site_user_inventory_site_created (site_id,remote_created_at,remote_user_id),
  CONSTRAINT fk_site_user_inventory_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_user_inventory_state CHECK ((remote_state in (_utf8mb4'normal',_utf8mb4'missing',_utf8mb4'deleted',_utf8mb4'identity_mismatch')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_user_inventory_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_role int NOT NULL,
  remote_status int NOT NULL,
  remote_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  hour_ts bigint NOT NULL,
  user_count bigint NOT NULL DEFAULT '0',
  new_user_count bigint NOT NULL DEFAULT '0',
  active_user_count bigint NOT NULL DEFAULT '0',
  quota bigint NOT NULL DEFAULT '0',
  used_quota bigint NOT NULL DEFAULT '0',
  request_count bigint NOT NULL DEFAULT '0',
  data_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version int NOT NULL,
  collected_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_user_inventory_hourly (site_id,remote_role,remote_status,remote_group,hour_ts),
  KEY idx_site_user_inventory_hourly_time (hour_ts,site_id),
  KEY idx_site_user_inventory_hourly_site_time (site_id,hour_ts),
  CONSTRAINT fk_site_user_inventory_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_user_inventory_hourly_status CHECK ((data_status = _utf8mb4'complete'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_channel_inventory (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_channel_id bigint NOT NULL,
  name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_type int NOT NULL,
  remote_status int NOT NULL,
  test_time bigint NOT NULL DEFAULT '0',
  response_time_ms bigint NOT NULL DEFAULT '0',
  balance decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  balance_updated_at bigint NOT NULL DEFAULT '0',
  models text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  used_quota bigint NOT NULL DEFAULT '0',
  priority bigint NOT NULL DEFAULT '0',
  weight bigint NOT NULL DEFAULT '0',
  auto_ban int NOT NULL DEFAULT '1',
  tag varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_inventory_site_remote (site_id,remote_channel_id),
  KEY idx_site_channel_inventory_site_state (site_id,remote_state,remote_channel_id),
  KEY idx_site_channel_inventory_site_status (site_id,remote_status,remote_channel_id),
  KEY idx_site_channel_inventory_site_type (site_id,remote_type,remote_channel_id),
  KEY idx_site_channel_inventory_site_group (site_id,remote_group,remote_channel_id),
  KEY idx_site_channel_inventory_site_tag (site_id,tag,remote_channel_id),
  CONSTRAINT fk_site_channel_inventory_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_channel_inventory_nonnegative CHECK (((response_time_ms >= 0) and (used_quota >= 0) and (priority >= 0) and (weight >= 0))),
  CONSTRAINT chk_site_channel_inventory_state CHECK ((remote_state in (_utf8mb4'normal',_utf8mb4'missing')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_channel_inventory_hourly (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  hour_ts bigint NOT NULL,
  channel_count bigint NOT NULL DEFAULT '0',
  available_count bigint NOT NULL DEFAULT '0',
  unavailable_count bigint NOT NULL DEFAULT '0',
  balance_total decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  response_time_avg_ms decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  response_time_max_ms bigint NOT NULL DEFAULT '0',
  availability_rate decimal(20,10) NOT NULL DEFAULT '0.0000000000',
  data_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version int NOT NULL,
  collected_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_inventory_hourly (site_id,hour_ts),
  KEY idx_site_channel_inventory_hourly_time (hour_ts,site_id),
  CONSTRAINT fk_site_channel_inventory_hourly_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_channel_inventory_hourly_status CHECK ((data_status = _utf8mb4'complete'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_performance_metric_bucket (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  bucket_ts bigint NOT NULL,
  series_schema varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  metric_source varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  avg_ttft_ms decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  avg_latency_ms decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  success_rate decimal(20,10) NOT NULL DEFAULT '0.0000000000',
  avg_tps decimal(30,10) NOT NULL DEFAULT '0.0000000000',
  request_count bigint DEFAULT NULL,
  success_count bigint DEFAULT NULL,
  total_latency_ms bigint DEFAULT NULL,
  ttft_sum_ms bigint DEFAULT NULL,
  ttft_count bigint DEFAULT NULL,
  output_tokens bigint DEFAULT NULL,
  generation_ms bigint DEFAULT NULL,
  config_version int NOT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_performance_metric_bucket (site_id,model_name,remote_group,bucket_ts),
  KEY idx_site_performance_metric_time (bucket_ts,site_id),
  KEY idx_site_performance_metric_site_time (site_id,bucket_ts),
  KEY idx_site_performance_metric_model_time (model_name,bucket_ts,site_id),
  CONSTRAINT fk_site_performance_metric_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_performance_metric_counters CHECK ((((metric_source = _utf8mb4'official_average') and (request_count is null) and (success_count is null) and (total_latency_ms is null) and (ttft_sum_ms is null) and (ttft_count is null) and (output_tokens is null) and (generation_ms is null)) or ((metric_source = _utf8mb4'counter_ready') and (request_count >= 0) and (success_count >= 0) and (success_count <= request_count) and (total_latency_ms >= 0) and (ttft_sum_ms >= 0) and (ttft_count >= 0) and (output_tokens >= 0) and (generation_ms >= 0)))),
  CONSTRAINT chk_site_performance_metric_nonnegative CHECK (((avg_ttft_ms >= 0) and (avg_latency_ms >= 0) and (success_rate >= 0) and (success_rate <= 1) and (avg_tps >= 0))),
  CONSTRAINT chk_site_performance_metric_source CHECK ((metric_source in (_utf8mb4'official_average',_utf8mb4'counter_ready')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_performance_collection_state (
  site_id bigint NOT NULL,
  capability_status varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_performance_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_performance_state_status CHECK ((capability_status in (_utf8mb4'available',_utf8mb4'average_only',_utf8mb4'unavailable')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_topup_order (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  amount bigint NOT NULL,
  money decimal(38,10) NOT NULL,
  payment_method varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  payment_provider varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  create_time bigint NOT NULL,
  complete_time bigint NOT NULL,
  remote_status varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_topup_order_remote (site_id,remote_id),
  KEY idx_site_topup_order_site_status (site_id,remote_status,remote_state),
  KEY idx_site_topup_order_provider_time (payment_provider,create_time,site_id),
  KEY idx_site_topup_order_user (site_id,remote_user_id),
  CONSTRAINT fk_site_topup_order_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_topup_order_state CHECK ((remote_state in (_utf8mb4'normal',_utf8mb4'missing'))),
  CONSTRAINT chk_site_topup_order_values CHECK (((remote_id > 0) and (remote_user_id >= 0) and (amount >= 0) and (money >= 0) and (create_time >= 0) and (complete_time >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_topup_collection_state (
  site_id bigint NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_total bigint NOT NULL DEFAULT '0',
  observed_max_id bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_topup_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_redemption (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  remote_user_id bigint NOT NULL,
  name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_status int NOT NULL,
  quota bigint NOT NULL,
  created_time bigint NOT NULL,
  redeemed_time bigint NOT NULL,
  used_user_id bigint NOT NULL,
  expired_time bigint NOT NULL,
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_redemption_remote (site_id,remote_id),
  KEY idx_site_redemption_site_status (site_id,remote_status,remote_state),
  KEY idx_site_redemption_expired (expired_time,site_id),
  KEY idx_site_redemption_user (site_id,used_user_id),
  CONSTRAINT fk_site_redemption_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_redemption_state CHECK ((remote_state in (_utf8mb4'normal',_utf8mb4'missing'))),
  CONSTRAINT chk_site_redemption_values CHECK (((remote_id > 0) and (remote_user_id >= 0) and (quota >= 0) and (created_time >= 0) and (redeemed_time >= 0) and (used_user_id >= 0) and (expired_time >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_redemption_collection_state (
  site_id bigint NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_total bigint NOT NULL DEFAULT '0',
  observed_max_id bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_redemption_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_upstream_task (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  remote_created_at bigint NOT NULL,
  remote_updated_at bigint NOT NULL,
  task_id varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  platform varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_user_id bigint NOT NULL,
  remote_group varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_channel_id bigint NOT NULL,
  quota bigint NOT NULL,
  action varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_status varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  submit_time bigint NOT NULL,
  start_time bigint NOT NULL,
  finish_time bigint NOT NULL,
  progress varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint NOT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_upstream_task_remote (site_id,remote_id),
  KEY idx_site_upstream_task_submit (site_id,submit_time,remote_id),
  KEY idx_site_upstream_task_status (site_id,remote_status,remote_updated_at),
  KEY idx_site_upstream_task_platform (platform,submit_time,site_id),
  KEY idx_site_upstream_task_public_id (site_id,task_id),
  CONSTRAINT fk_site_upstream_task_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_upstream_task_values CHECK (((remote_id > 0) and (remote_created_at >= 0) and (remote_updated_at >= remote_created_at) and (remote_user_id >= 0) and (remote_channel_id >= 0) and (quota >= 0) and (submit_time >= 0) and (start_time >= 0) and (finish_time >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_upstream_task_collection_state (
  site_id bigint NOT NULL,
  overlap_start bigint NOT NULL DEFAULT '0',
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_upstream_task_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_model_meta (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  model_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  description text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  icon varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  tags varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  vendor_id bigint NOT NULL,
  remote_status int NOT NULL,
  sync_official int NOT NULL,
  name_rule int NOT NULL,
  remote_created_time bigint NOT NULL,
  remote_updated_time bigint NOT NULL,
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version int NOT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_model_remote (site_id,remote_id),
  KEY idx_site_model_name (site_id,model_name,name_rule),
  KEY idx_site_model_vendor (vendor_id,remote_status,site_id),
  CONSTRAINT fk_site_model_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_model_values CHECK (((remote_id > 0) and (vendor_id >= 0) and (name_rule between 0 and 3) and (remote_created_time >= 0) and (remote_updated_time >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_model_meta_collection_state (
  site_id bigint NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_model_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_channel_model_mapping (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_channel_id bigint NOT NULL,
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_group varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  config_version int NOT NULL,
  collected_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_model_group (site_id,remote_channel_id,model_name,remote_group),
  KEY idx_site_channel_model_name (site_id,model_name),
  CONSTRAINT fk_site_channel_model_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_subscription_plan (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  title varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  subtitle varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  price_amount decimal(38,10) NOT NULL,
  currency varchar(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  duration_unit varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  duration_value int NOT NULL,
  custom_seconds bigint NOT NULL,
  enabled tinyint(1) NOT NULL,
  sort_order int NOT NULL,
  total_amount bigint NOT NULL,
  quota_reset_period varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quota_reset_custom_seconds bigint NOT NULL,
  remote_created_at bigint NOT NULL,
  remote_updated_at bigint NOT NULL,
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_subscription_plan_remote (site_id,remote_id),
  KEY idx_site_subscription_plan_state (site_id,remote_state,sort_order),
  CONSTRAINT fk_site_subscription_plan_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_subscription_plan_values CHECK (((remote_id > 0) and (price_amount >= 0) and (duration_value > 0) and (custom_seconds >= 0) and (total_amount >= 0) and (quota_reset_custom_seconds >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_subscription_plan_collection_state (
  site_id bigint NOT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_subscription_plan_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_group_catalog (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  group_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  ratio_decimal decimal(38,18) DEFAULT NULL,
  description varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  root_visible tinyint(1) NOT NULL DEFAULT '0',
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_group_catalog_name (site_id,group_name),
  KEY idx_site_group_catalog_state (site_id,remote_state,group_name),
  CONSTRAINT fk_site_group_catalog_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_group_catalog_values CHECK (((ratio_decimal is null) or (ratio_decimal >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_pricing_catalog (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  model_name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  vendor_key varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  vendor_id bigint NOT NULL,
  description text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  icon varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  tags varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  owner_by varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  quota_type bigint NOT NULL,
  model_ratio decimal(38,18) NOT NULL,
  model_price decimal(38,18) NOT NULL,
  completion_ratio decimal(38,18) NOT NULL,
  cache_ratio decimal(38,18) DEFAULT NULL,
  create_cache_ratio decimal(38,18) DEFAULT NULL,
  image_ratio decimal(38,18) DEFAULT NULL,
  audio_ratio decimal(38,18) DEFAULT NULL,
  audio_completion_ratio decimal(38,18) DEFAULT NULL,
  enable_groups_json json NOT NULL,
  supported_endpoint_types_json json NOT NULL,
  pricing_version varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  root_visible tinyint(1) NOT NULL DEFAULT '1',
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count int NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint DEFAULT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_pricing_catalog_identity (site_id,model_name,vendor_key),
  KEY idx_site_pricing_catalog_state (site_id,remote_state,model_name),
  KEY idx_site_pricing_catalog_vendor (site_id,vendor_key,remote_state),
  CONSTRAINT fk_site_pricing_catalog_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_pricing_catalog_values CHECK (((vendor_id >= 0) and (quota_type in (0,1)) and (model_ratio >= 0) and (model_price >= 0) and (completion_ratio >= 0) and ((cache_ratio is null) or (cache_ratio >= 0)) and ((create_cache_ratio is null) or (create_cache_ratio >= 0)) and ((image_ratio is null) or (image_ratio >= 0)) and ((audio_ratio is null) or (audio_ratio >= 0)) and ((audio_completion_ratio is null) or (audio_completion_ratio >= 0))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS pricing_group_collection_state (
  site_id bigint NOT NULL,
  resource_kind varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  as_of bigint DEFAULT NULL,
  last_complete_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id,resource_kind),
  KEY idx_pricing_group_state_status (resource_kind,data_status,updated_at),
  CONSTRAINT fk_pricing_group_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_pricing_group_state_values CHECK (((resource_kind in (_utf8mb4'group',_utf8mb4'pricing')) and (observed_count >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_system_task (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  remote_id bigint NOT NULL,
  remote_task_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  task_type varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  error_present tinyint(1) NOT NULL DEFAULT '0',
  error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  total bigint DEFAULT NULL,
  processed bigint DEFAULT NULL,
  progress bigint DEFAULT NULL,
  remaining bigint DEFAULT NULL,
  deleted_count bigint DEFAULT NULL,
  tested bigint DEFAULT NULL,
  succeeded bigint DEFAULT NULL,
  failed bigint DEFAULT NULL,
  disabled bigint DEFAULT NULL,
  enabled bigint DEFAULT NULL,
  checked_channels bigint DEFAULT NULL,
  changed_channels bigint DEFAULT NULL,
  detected_add_models bigint DEFAULT NULL,
  detected_remove_models bigint DEFAULT NULL,
  failed_channels bigint DEFAULT NULL,
  auto_added_models bigint DEFAULT NULL,
  unfinished_tasks bigint DEFAULT NULL,
  channels_scanned bigint DEFAULT NULL,
  platforms_scanned bigint DEFAULT NULL,
  null_tasks_failed bigint DEFAULT NULL,
  remote_created_at bigint NOT NULL,
  remote_updated_at bigint NOT NULL,
  source_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version int NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint NOT NULL,
  collected_at bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_system_task_remote (site_id,remote_id),
  UNIQUE KEY uk_site_system_task_task_id (site_id,remote_task_id),
  KEY idx_site_system_task_type_status (site_id,task_type,remote_status,remote_updated_at),
  KEY idx_site_system_task_terminal_retention (remote_status,remote_updated_at,site_id),
  CONSTRAINT fk_site_system_task_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_system_task_values CHECK (((remote_id > 0) and (remote_created_at >= 0) and (remote_updated_at >= remote_created_at) and ((progress is null) or (progress between 0 and 100))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_system_task_collection_state (
  site_id bigint NOT NULL,
  resource_kind varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  truncated tinyint(1) NOT NULL DEFAULT '0',
  id_gap tinyint(1) NOT NULL DEFAULT '0',
  as_of bigint DEFAULT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  last_error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count bigint NOT NULL DEFAULT '0',
  config_version int NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (site_id,resource_kind),
  KEY idx_site_system_task_state_status (resource_kind,data_status,updated_at),
  CONSTRAINT fk_site_system_task_state_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_system_task_state_values CHECK (((resource_kind in (_utf8mb4'list',_utf8mb4'current:log_cleanup',_utf8mb4'current:channel_test',_utf8mb4'current:model_update',_utf8mb4'current:midjourney_poll',_utf8mb4'current:async_task_poll')) and (observed_count >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS data_maintenance_state (
  id bigint NOT NULL AUTO_INCREMENT,
  operation_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope_key varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope_revision char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  date_key int NOT NULL DEFAULT '0',
  status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  cursor_kind varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  cursor_site_id bigint NOT NULL DEFAULT '0',
  cursor_node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  cursor_bucket_start bigint NOT NULL DEFAULT '0',
  cursor_id bigint NOT NULL DEFAULT '0',
  site_id bigint DEFAULT NULL,
  site_config_version bigint DEFAULT NULL,
  request_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  run_id bigint DEFAULT NULL,
  error_code varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  attempt_count int NOT NULL DEFAULT '0',
  next_attempt_at bigint NOT NULL DEFAULT '0',
  last_attempt_at bigint DEFAULT NULL,
  last_success_at bigint DEFAULT NULL,
  last_failure_at bigint DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_data_maintenance_scope (operation_id,scope_key),
  KEY idx_data_maintenance_due (status,next_attempt_at,id),
  KEY idx_data_maintenance_site (site_id,site_config_version,operation_id),
  KEY fk_data_maintenance_run (run_id),
  CONSTRAINT fk_data_maintenance_run FOREIGN KEY (run_id) REFERENCES collection_run (id) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT fk_data_maintenance_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_data_maintenance_attempt CHECK (((attempt_count >= 0) and (next_attempt_at >= 0) and (created_at > 0) and (updated_at >= created_at) and ((last_attempt_at is null) or (last_attempt_at >= 0)) and ((last_success_at is null) or (last_success_at >= 0)) and ((last_failure_at is null) or (last_failure_at >= 0)))),
  CONSTRAINT chk_data_maintenance_cursor CHECK (((date_key >= 0) and (cursor_site_id >= 0) and (cursor_bucket_start >= 0) and (cursor_id >= 0))),
  CONSTRAINT chk_data_maintenance_operation CHECK ((operation_id in (_utf8mb4'authorize_pricing_group_sync',_utf8mb4'resource_daily_finalize',_utf8mb4'resource_rollup_gap_repair',_utf8mb4'collection_run_error_redaction',_utf8mb4'metadata_diagnostic_run_cleanup'))),
  CONSTRAINT chk_data_maintenance_shape CHECK ((((operation_id = _utf8mb4'authorize_pricing_group_sync') and (date_key = 0) and (site_id is not null) and (site_config_version is not null) and (scope_key = concat(_utf8mb4'site:',site_id,_utf8mb4':config:',site_config_version)) and (scope_revision = _utf8mb4'') and (request_id <> _utf8mb4'')) or ((operation_id in (_utf8mb4'resource_daily_finalize',_utf8mb4'resource_rollup_gap_repair')) and (scope_key = _utf8mb4'global') and (site_id is null) and (site_config_version is null) and (request_id = _utf8mb4'') and (((date_key = 0) and (status = _utf8mb4'pending') and (scope_revision = _utf8mb4'')) or ((date_key > 0) and regexp_like(scope_revision,_utf8mb4'^[0-9a-f]{64}$')))) or ((operation_id in (_utf8mb4'collection_run_error_redaction',_utf8mb4'metadata_diagnostic_run_cleanup')) and (scope_key = _utf8mb4'global') and (site_id is null) and (site_config_version is null) and (request_id = _utf8mb4'') and (scope_revision = _utf8mb4'')))),
  CONSTRAINT chk_data_maintenance_site_pair CHECK ((((site_id is null) and (site_config_version is null)) or ((site_id > 0) and (site_config_version > 0)))),
  CONSTRAINT chk_data_maintenance_status CHECK ((status in (_utf8mb4'pending',_utf8mb4'running',_utf8mb4'complete',_utf8mb4'failed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_instance_lifecycle (
  id bigint NOT NULL AUTO_INCREMENT,
  site_id bigint NOT NULL,
  node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  start_minute_ts bigint NOT NULL,
  end_minute_ts bigint DEFAULT NULL,
  evidence_status varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'known',
  open_node_name varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin GENERATED ALWAYS AS ((case when (end_minute_ts is null) then node_name else NULL end)) STORED,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_instance_lifecycle_start (site_id,node_name,start_minute_ts),
  UNIQUE KEY uk_site_instance_lifecycle_open (site_id,open_node_name),
  KEY idx_site_instance_lifecycle_range (site_id,start_minute_ts,end_minute_ts,node_name),
  CONSTRAINT fk_site_instance_lifecycle_site FOREIGN KEY (site_id) REFERENCES site (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_instance_lifecycle_range CHECK (((start_minute_ts > 0) and ((start_minute_ts % 60) = 0) and ((end_minute_ts is null) or ((end_minute_ts >= start_minute_ts) and ((end_minute_ts % 60) = 0))) and (evidence_status in (_utf8mb4'known',_utf8mb4'legacy_unknown')) and (created_at > 0) and (updated_at >= created_at)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
