CREATE TABLE IF NOT EXISTS site_user_inventory (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_user_id BIGINT NOT NULL,
  remote_created_at BIGINT NOT NULL,
  username VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  display_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_role INT NOT NULL,
  remote_status INT NOT NULL,
  remote_group VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  quota BIGINT NOT NULL DEFAULT 0,
  used_quota BIGINT NOT NULL DEFAULT 0,
  request_count BIGINT NOT NULL DEFAULT 0,
  last_login_at BIGINT NOT NULL DEFAULT 0,
  remote_state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_user_inventory_site_remote (site_id, remote_user_id),
  KEY idx_site_user_inventory_site_state (site_id, remote_state, remote_user_id),
  KEY idx_site_user_inventory_site_role (site_id, remote_role, remote_user_id),
  KEY idx_site_user_inventory_site_status (site_id, remote_status, remote_user_id),
  KEY idx_site_user_inventory_site_group (site_id, remote_group, remote_user_id),
  KEY idx_site_user_inventory_site_login (site_id, last_login_at, remote_user_id),
  KEY idx_site_user_inventory_site_created (site_id, remote_created_at, remote_user_id),
  CONSTRAINT fk_site_user_inventory_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_user_inventory_state CHECK (remote_state IN ('normal','missing','deleted','identity_mismatch'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_user_inventory_hourly (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_role INT NOT NULL,
  remote_status INT NOT NULL,
  remote_group VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  hour_ts BIGINT NOT NULL,
  user_count BIGINT NOT NULL DEFAULT 0,
  new_user_count BIGINT NOT NULL DEFAULT 0,
  active_user_count BIGINT NOT NULL DEFAULT 0,
  quota BIGINT NOT NULL DEFAULT 0,
  used_quota BIGINT NOT NULL DEFAULT 0,
  request_count BIGINT NOT NULL DEFAULT 0,
  data_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version INT NOT NULL,
  collected_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_user_inventory_hourly (site_id, remote_role, remote_status, remote_group, hour_ts),
  KEY idx_site_user_inventory_hourly_time (hour_ts, site_id),
  KEY idx_site_user_inventory_hourly_site_time (site_id, hour_ts),
  CONSTRAINT fk_site_user_inventory_hourly_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_user_inventory_hourly_status CHECK (data_status IN ('complete'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
