CREATE TABLE IF NOT EXISTS site_channel_inventory (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_channel_id BIGINT NOT NULL,
  name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_type INT NOT NULL,
  remote_status INT NOT NULL,
  test_time BIGINT NOT NULL DEFAULT 0,
  response_time_ms BIGINT NOT NULL DEFAULT 0,
  balance DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  balance_updated_at BIGINT NOT NULL DEFAULT 0,
  models TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_group VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  used_quota BIGINT NOT NULL DEFAULT 0,
  priority BIGINT NOT NULL DEFAULT 0,
  weight BIGINT NOT NULL DEFAULT 0,
  auto_ban INT NOT NULL DEFAULT 1,
  tag VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_inventory_site_remote (site_id, remote_channel_id),
  KEY idx_site_channel_inventory_site_state (site_id, remote_state, remote_channel_id),
  KEY idx_site_channel_inventory_site_status (site_id, remote_status, remote_channel_id),
  KEY idx_site_channel_inventory_site_type (site_id, remote_type, remote_channel_id),
  KEY idx_site_channel_inventory_site_group (site_id, remote_group, remote_channel_id),
  KEY idx_site_channel_inventory_site_tag (site_id, tag, remote_channel_id),
  CONSTRAINT fk_site_channel_inventory_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_channel_inventory_state CHECK (remote_state IN ('normal','missing')),
  CONSTRAINT chk_site_channel_inventory_nonnegative CHECK (response_time_ms >= 0 AND used_quota >= 0 AND priority >= 0 AND weight >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_channel_inventory_hourly (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  hour_ts BIGINT NOT NULL,
  channel_count BIGINT NOT NULL DEFAULT 0,
  available_count BIGINT NOT NULL DEFAULT 0,
  unavailable_count BIGINT NOT NULL DEFAULT 0,
  balance_total DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  response_time_avg_ms DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  response_time_max_ms BIGINT NOT NULL DEFAULT 0,
  availability_rate DECIMAL(20,10) NOT NULL DEFAULT 0.0000000000,
  data_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version INT NOT NULL,
  collected_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_channel_inventory_hourly (site_id, hour_ts),
  KEY idx_site_channel_inventory_hourly_time (hour_ts, site_id),
  CONSTRAINT fk_site_channel_inventory_hourly_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_channel_inventory_hourly_status CHECK (data_status IN ('complete'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
