CREATE TABLE IF NOT EXISTS site_performance_metric_bucket (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  model_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_group VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  bucket_ts BIGINT NOT NULL,
  series_schema VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  metric_source VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  avg_ttft_ms DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  avg_latency_ms DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  success_rate DECIMAL(20,10) NOT NULL DEFAULT 0.0000000000,
  avg_tps DECIMAL(30,10) NOT NULL DEFAULT 0.0000000000,
  request_count BIGINT NULL,
  success_count BIGINT NULL,
  total_latency_ms BIGINT NULL,
  ttft_sum_ms BIGINT NULL,
  ttft_count BIGINT NULL,
  output_tokens BIGINT NULL,
  generation_ms BIGINT NULL,
  config_version INT NOT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_performance_metric_bucket (site_id, model_name, remote_group, bucket_ts),
  KEY idx_site_performance_metric_time (bucket_ts, site_id),
  KEY idx_site_performance_metric_site_time (site_id, bucket_ts),
  KEY idx_site_performance_metric_model_time (model_name, bucket_ts, site_id),
  CONSTRAINT fk_site_performance_metric_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_performance_metric_source CHECK (metric_source IN ('official_average','counter_ready')),
  CONSTRAINT chk_site_performance_metric_nonnegative CHECK (avg_ttft_ms >= 0 AND avg_latency_ms >= 0 AND success_rate >= 0 AND success_rate <= 1 AND avg_tps >= 0),
  CONSTRAINT chk_site_performance_metric_counters CHECK ((metric_source = 'official_average' AND request_count IS NULL AND success_count IS NULL AND total_latency_ms IS NULL AND ttft_sum_ms IS NULL AND ttft_count IS NULL AND output_tokens IS NULL AND generation_ms IS NULL) OR (metric_source = 'counter_ready' AND request_count >= 0 AND success_count >= 0 AND success_count <= request_count AND total_latency_ms >= 0 AND ttft_sum_ms >= 0 AND ttft_count >= 0 AND output_tokens >= 0 AND generation_ms >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_performance_collection_state (
  site_id BIGINT NOT NULL,
  capability_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_performance_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_performance_state_status CHECK (capability_status IN ('available','average_only','unavailable'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
