CREATE TABLE IF NOT EXISTS site_topup_order (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_id BIGINT NOT NULL,
  remote_user_id BIGINT NOT NULL,
  amount BIGINT NOT NULL,
  money DECIMAL(38,10) NOT NULL,
  payment_method VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  payment_provider VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  create_time BIGINT NOT NULL,
  complete_time BIGINT NOT NULL,
  remote_status VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_topup_order_remote (site_id, remote_id),
  KEY idx_site_topup_order_site_status (site_id, remote_status, remote_state),
  KEY idx_site_topup_order_provider_time (payment_provider, create_time, site_id),
  KEY idx_site_topup_order_user (site_id, remote_user_id),
  CONSTRAINT fk_site_topup_order_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_topup_order_values CHECK (remote_id > 0 AND remote_user_id >= 0 AND amount >= 0 AND money >= 0 AND create_time >= 0 AND complete_time >= 0),
  CONSTRAINT chk_site_topup_order_state CHECK (remote_state IN ('normal','missing'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_topup_collection_state (
  site_id BIGINT NOT NULL,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_total BIGINT NOT NULL DEFAULT 0,
  observed_max_id BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_topup_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_redemption (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_id BIGINT NOT NULL,
  remote_user_id BIGINT NOT NULL,
  name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_status INT NOT NULL,
  quota BIGINT NOT NULL,
  created_time BIGINT NOT NULL,
  redeemed_time BIGINT NOT NULL,
  used_user_id BIGINT NOT NULL,
  expired_time BIGINT NOT NULL,
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_redemption_remote (site_id, remote_id),
  KEY idx_site_redemption_site_status (site_id, remote_status, remote_state),
  KEY idx_site_redemption_expired (expired_time, site_id),
  KEY idx_site_redemption_user (site_id, used_user_id),
  CONSTRAINT fk_site_redemption_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_redemption_values CHECK (remote_id > 0 AND remote_user_id >= 0 AND quota >= 0 AND created_time >= 0 AND redeemed_time >= 0 AND used_user_id >= 0 AND expired_time >= 0),
  CONSTRAINT chk_site_redemption_state CHECK (remote_state IN ('normal','missing'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_redemption_collection_state (
  site_id BIGINT NOT NULL,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_total BIGINT NOT NULL DEFAULT 0,
  observed_max_id BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_redemption_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
