CREATE TABLE IF NOT EXISTS site_upstream_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_id BIGINT NOT NULL,
  remote_created_at BIGINT NOT NULL,
  remote_updated_at BIGINT NOT NULL,
  task_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  platform VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  remote_user_id BIGINT NOT NULL,
  remote_group VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_channel_id BIGINT NOT NULL,
  quota BIGINT NOT NULL,
  action VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  remote_status VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  submit_time BIGINT NOT NULL,
  start_time BIGINT NOT NULL,
  finish_time BIGINT NOT NULL,
  progress VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  model_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_upstream_task_remote (site_id, remote_id),
  KEY idx_site_upstream_task_submit (site_id, submit_time, remote_id),
  KEY idx_site_upstream_task_status (site_id, remote_status, remote_updated_at),
  KEY idx_site_upstream_task_platform (platform, submit_time, site_id),
  KEY idx_site_upstream_task_public_id (site_id, task_id),
  CONSTRAINT fk_site_upstream_task_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_upstream_task_values CHECK (remote_id > 0 AND remote_created_at >= 0 AND remote_updated_at >= remote_created_at AND remote_user_id >= 0 AND remote_channel_id >= 0 AND quota >= 0 AND submit_time >= 0 AND start_time >= 0 AND finish_time >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_upstream_task_collection_state (
  site_id BIGINT NOT NULL,
  overlap_start BIGINT NOT NULL DEFAULT 0,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id),
  CONSTRAINT fk_site_upstream_task_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
