CREATE TABLE IF NOT EXISTS site_subscription_plan (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_id BIGINT NOT NULL,
  title VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  subtitle VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  price_amount DECIMAL(38,10) NOT NULL,
  currency VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  duration_unit VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  duration_value INT NOT NULL,
  custom_seconds BIGINT NOT NULL,
  enabled TINYINT(1) NOT NULL,
  sort_order INT NOT NULL,
  total_amount BIGINT NOT NULL,
  quota_reset_period VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quota_reset_custom_seconds BIGINT NOT NULL,
  remote_created_at BIGINT NOT NULL,
  remote_updated_at BIGINT NOT NULL,
  source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY(id),
  UNIQUE KEY uk_site_subscription_plan_remote(site_id,remote_id),
  KEY idx_site_subscription_plan_state(site_id,remote_state,sort_order),
  CONSTRAINT fk_site_subscription_plan_site FOREIGN KEY(site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_subscription_plan_values CHECK(remote_id>0 AND price_amount>=0 AND duration_value>0 AND custom_seconds>=0 AND total_amount>=0 AND quota_reset_custom_seconds>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_subscription_plan_collection_state (
  site_id BIGINT NOT NULL,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY(site_id),
  CONSTRAINT fk_site_subscription_plan_state_site FOREIGN KEY(site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
