CREATE TABLE IF NOT EXISTS site_group_catalog (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  group_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  ratio_decimal DECIMAL(38,18) NULL,
  description VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  root_visible TINYINT(1) NOT NULL DEFAULT 0,
  source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_group_catalog_name (site_id, group_name),
  KEY idx_site_group_catalog_state (site_id, remote_state, group_name),
  CONSTRAINT fk_site_group_catalog_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_group_catalog_values CHECK (ratio_decimal IS NULL OR ratio_decimal >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_pricing_catalog (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  model_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  vendor_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  vendor_id BIGINT NOT NULL,
  description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  icon VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  tags VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  owner_by VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  quota_type BIGINT NOT NULL,
  model_ratio DECIMAL(38,18) NOT NULL,
  model_price DECIMAL(38,18) NOT NULL,
  completion_ratio DECIMAL(38,18) NOT NULL,
  cache_ratio DECIMAL(38,18) NULL,
  create_cache_ratio DECIMAL(38,18) NULL,
  image_ratio DECIMAL(38,18) NULL,
  audio_ratio DECIMAL(38,18) NULL,
  audio_completion_ratio DECIMAL(38,18) NULL,
  enable_groups_json JSON NOT NULL,
  supported_endpoint_types_json JSON NOT NULL,
  pricing_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  root_visible TINYINT(1) NOT NULL DEFAULT 1,
  source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  missing_count INT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_pricing_catalog_identity (site_id, model_name, vendor_key),
  KEY idx_site_pricing_catalog_state (site_id, remote_state, model_name),
  KEY idx_site_pricing_catalog_vendor (site_id, vendor_key, remote_state),
  CONSTRAINT fk_site_pricing_catalog_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_pricing_catalog_values CHECK (vendor_id >= 0 AND quota_type IN (0,1) AND model_ratio >= 0 AND model_price >= 0 AND completion_ratio >= 0 AND (cache_ratio IS NULL OR cache_ratio >= 0) AND (create_cache_ratio IS NULL OR create_cache_ratio >= 0) AND (image_ratio IS NULL OR image_ratio >= 0) AND (audio_ratio IS NULL OR audio_ratio >= 0) AND (audio_completion_ratio IS NULL OR audio_completion_ratio >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS pricing_group_collection_state (
  site_id BIGINT NOT NULL,
  resource_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  as_of BIGINT NULL,
  last_complete_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id, resource_kind),
  KEY idx_pricing_group_state_status (resource_kind, data_status, updated_at),
  CONSTRAINT fk_pricing_group_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_pricing_group_state_values CHECK (resource_kind IN ('group','pricing') AND observed_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
