CREATE TABLE IF NOT EXISTS site_system_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  site_id BIGINT NOT NULL,
  remote_id BIGINT NOT NULL,
  remote_task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  task_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  error_present TINYINT(1) NOT NULL DEFAULT 0,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  total BIGINT NULL,
  processed BIGINT NULL,
  progress BIGINT NULL,
  remaining BIGINT NULL,
  deleted_count BIGINT NULL,
  tested BIGINT NULL,
  succeeded BIGINT NULL,
  failed BIGINT NULL,
  disabled BIGINT NULL,
  enabled BIGINT NULL,
  checked_channels BIGINT NULL,
  changed_channels BIGINT NULL,
  detected_add_models BIGINT NULL,
  detected_remove_models BIGINT NULL,
  failed_channels BIGINT NULL,
  auto_added_models BIGINT NULL,
  unfinished_tasks BIGINT NULL,
  channels_scanned BIGINT NULL,
  platforms_scanned BIGINT NULL,
  null_tasks_failed BIGINT NULL,
  remote_created_at BIGINT NOT NULL,
  remote_updated_at BIGINT NOT NULL,
  source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  config_version INT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  collected_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_site_system_task_remote (site_id, remote_id),
  UNIQUE KEY uk_site_system_task_task_id (site_id, remote_task_id),
  KEY idx_site_system_task_type_status (site_id, task_type, remote_status, remote_updated_at),
  KEY idx_site_system_task_terminal_retention (remote_status, remote_updated_at, site_id),
  CONSTRAINT fk_site_system_task_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_system_task_values CHECK (remote_id > 0 AND remote_created_at >= 0 AND remote_updated_at >= remote_created_at AND (progress IS NULL OR progress BETWEEN 0 AND 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS site_system_task_collection_state (
  site_id BIGINT NOT NULL,
  resource_kind VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  truncated TINYINT(1) NOT NULL DEFAULT 0,
  id_gap TINYINT(1) NOT NULL DEFAULT 0,
  as_of BIGINT NULL,
  last_success_at BIGINT NULL,
  last_failure_at BIGINT NULL,
  last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  observed_count BIGINT NOT NULL DEFAULT 0,
  config_version INT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (site_id, resource_kind),
  KEY idx_site_system_task_state_status (resource_kind, data_status, updated_at),
  CONSTRAINT fk_site_system_task_state_site FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_site_system_task_state_values CHECK (resource_kind IN ('list','current:log_cleanup','current:channel_test','current:model_update','current:midjourney_poll','current:async_task_poll') AND observed_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
