/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUserInventoryRouteImport } from './routes/_authenticated/user-inventory'
import { Route as AuthenticatedUpstreamTasksRouteImport } from './routes/_authenticated/upstream-tasks'
import { Route as AuthenticatedSystemTasksRouteImport } from './routes/_authenticated/system-tasks'
import { Route as AuthenticatedSubscriptionPlansRouteImport } from './routes/_authenticated/subscription-plans'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites_'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedPricingGroupsRouteImport } from './routes/_authenticated/pricing-groups'
import { Route as AuthenticatedPerformanceHistoryRouteImport } from './routes/_authenticated/performance-history'
import { Route as AuthenticatedModelCatalogRouteImport } from './routes/_authenticated/model-catalog'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedFinancialOperationsRouteImport } from './routes/_authenticated/financial-operations'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers_'
import { Route as AuthenticatedChannelInventoryRouteImport } from './routes/_authenticated/channel-inventory'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts_'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedStatisticsTokensRouteImport } from './routes/_authenticated/statistics/tokens'
import { Route as AuthenticatedStatisticsSitesRouteImport } from './routes/_authenticated/statistics/sites'
import { Route as AuthenticatedStatisticsNodesRouteImport } from './routes/_authenticated/statistics/nodes'
import { Route as AuthenticatedStatisticsModelsRouteImport } from './routes/_authenticated/statistics/models'
import { Route as AuthenticatedStatisticsGroupsRouteImport } from './routes/_authenticated/statistics/groups'
import { Route as AuthenticatedStatisticsGlobalRouteImport } from './routes/_authenticated/statistics/global'
import { Route as AuthenticatedStatisticsCustomersRouteImport } from './routes/_authenticated/statistics/customers'
import { Route as AuthenticatedStatisticsChannelsRouteImport } from './routes/_authenticated/statistics/channels'
import { Route as AuthenticatedStatisticsAccountsRouteImport } from './routes/_authenticated/statistics/accounts'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSitesSiteIdIndexRouteImport } from './routes/_authenticated/sites/$siteId/index'
import { Route as AuthenticatedCustomersCustomerIdIndexRouteImport } from './routes/_authenticated/customers/$customerId/index'
import { Route as AuthenticatedAccountsAccountIdIndexRouteImport } from './routes/_authenticated/accounts/$accountId/index'
import { Route as AuthenticatedSitesSiteIdUserInventoryRouteImport } from './routes/_authenticated/sites/$siteId/user-inventory'
import { Route as AuthenticatedSitesSiteIdUpstreamTasksRouteImport } from './routes/_authenticated/sites/$siteId/upstream-tasks'
import { Route as AuthenticatedSitesSiteIdSystemTasksRouteImport } from './routes/_authenticated/sites/$siteId/system-tasks'
import { Route as AuthenticatedSitesSiteIdSubscriptionPlansRouteImport } from './routes/_authenticated/sites/$siteId/subscription-plans'
import { Route as AuthenticatedSitesSiteIdStatusRouteImport } from './routes/_authenticated/sites/$siteId/status'
import { Route as AuthenticatedSitesSiteIdStatsRouteImport } from './routes/_authenticated/sites/$siteId/stats'
import { Route as AuthenticatedSitesSiteIdRankingsRouteImport } from './routes/_authenticated/sites/$siteId/rankings'
import { Route as AuthenticatedSitesSiteIdPricingGroupsRouteImport } from './routes/_authenticated/sites/$siteId/pricing-groups'
import { Route as AuthenticatedSitesSiteIdPerformanceHistoryRouteImport } from './routes/_authenticated/sites/$siteId/performance-history'
import { Route as AuthenticatedSitesSiteIdModelCatalogRouteImport } from './routes/_authenticated/sites/$siteId/model-catalog'
import { Route as AuthenticatedSitesSiteIdLogsRouteImport } from './routes/_authenticated/sites/$siteId/logs'
import { Route as AuthenticatedSitesSiteIdFinancialOperationsRouteImport } from './routes/_authenticated/sites/$siteId/financial-operations'
import { Route as AuthenticatedSitesSiteIdCollectionRunsRouteImport } from './routes/_authenticated/sites/$siteId/collection-runs'
import { Route as AuthenticatedSitesSiteIdChannelInventoryRouteImport } from './routes/_authenticated/sites/$siteId/channel-inventory'
import { Route as AuthenticatedCustomersCustomerIdStatsRouteImport } from './routes/_authenticated/customers/$customerId/stats'
import { Route as AuthenticatedAccountsAccountIdStatsRouteImport } from './routes/_authenticated/accounts/$accountId/stats'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserInventoryRoute =
  AuthenticatedUserInventoryRouteImport.update({
    id: '/user-inventory',
    path: '/user-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUpstreamTasksRoute =
  AuthenticatedUpstreamTasksRouteImport.update({
    id: '/upstream-tasks',
    path: '/upstream-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemTasksRoute =
  AuthenticatedSystemTasksRouteImport.update({
    id: '/system-tasks',
    path: '/system-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionPlansRoute =
  AuthenticatedSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites_',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingGroupsRoute =
  AuthenticatedPricingGroupsRouteImport.update({
    id: '/pricing-groups',
    path: '/pricing-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceHistoryRoute =
  AuthenticatedPerformanceHistoryRouteImport.update({
    id: '/performance-history',
    path: '/performance-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelCatalogRoute =
  AuthenticatedModelCatalogRouteImport.update({
    id: '/model-catalog',
    path: '/model-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialOperationsRoute =
  AuthenticatedFinancialOperationsRouteImport.update({
    id: '/financial-operations',
    path: '/financial-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers_',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelInventoryRoute =
  AuthenticatedChannelInventoryRouteImport.update({
    id: '/channel-inventory',
    path: '/channel-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts_',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsTokensRoute =
  AuthenticatedStatisticsTokensRouteImport.update({
    id: '/statistics/tokens',
    path: '/statistics/tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsSitesRoute =
  AuthenticatedStatisticsSitesRouteImport.update({
    id: '/statistics/sites',
    path: '/statistics/sites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsNodesRoute =
  AuthenticatedStatisticsNodesRouteImport.update({
    id: '/statistics/nodes',
    path: '/statistics/nodes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsModelsRoute =
  AuthenticatedStatisticsModelsRouteImport.update({
    id: '/statistics/models',
    path: '/statistics/models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsGroupsRoute =
  AuthenticatedStatisticsGroupsRouteImport.update({
    id: '/statistics/groups',
    path: '/statistics/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsGlobalRoute =
  AuthenticatedStatisticsGlobalRouteImport.update({
    id: '/statistics/global',
    path: '/statistics/global',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsCustomersRoute =
  AuthenticatedStatisticsCustomersRouteImport.update({
    id: '/statistics/customers',
    path: '/statistics/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsChannelsRoute =
  AuthenticatedStatisticsChannelsRouteImport.update({
    id: '/statistics/channels',
    path: '/statistics/channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsAccountsRoute =
  AuthenticatedStatisticsAccountsRouteImport.update({
    id: '/statistics/accounts',
    path: '/statistics/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdIndexRoute =
  AuthenticatedSitesSiteIdIndexRouteImport.update({
    id: '/sites/$siteId/',
    path: '/sites/$siteId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdIndexRoute =
  AuthenticatedCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdIndexRoute =
  AuthenticatedAccountsAccountIdIndexRouteImport.update({
    id: '/accounts/$accountId/',
    path: '/accounts/$accountId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdUserInventoryRoute =
  AuthenticatedSitesSiteIdUserInventoryRouteImport.update({
    id: '/sites/$siteId/user-inventory',
    path: '/sites/$siteId/user-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdUpstreamTasksRoute =
  AuthenticatedSitesSiteIdUpstreamTasksRouteImport.update({
    id: '/sites/$siteId/upstream-tasks',
    path: '/sites/$siteId/upstream-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdSystemTasksRoute =
  AuthenticatedSitesSiteIdSystemTasksRouteImport.update({
    id: '/sites/$siteId/system-tasks',
    path: '/sites/$siteId/system-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdSubscriptionPlansRoute =
  AuthenticatedSitesSiteIdSubscriptionPlansRouteImport.update({
    id: '/sites/$siteId/subscription-plans',
    path: '/sites/$siteId/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdStatusRoute =
  AuthenticatedSitesSiteIdStatusRouteImport.update({
    id: '/sites/$siteId/status',
    path: '/sites/$siteId/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdStatsRoute =
  AuthenticatedSitesSiteIdStatsRouteImport.update({
    id: '/sites/$siteId/stats',
    path: '/sites/$siteId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdRankingsRoute =
  AuthenticatedSitesSiteIdRankingsRouteImport.update({
    id: '/sites/$siteId/rankings',
    path: '/sites/$siteId/rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPricingGroupsRoute =
  AuthenticatedSitesSiteIdPricingGroupsRouteImport.update({
    id: '/sites/$siteId/pricing-groups',
    path: '/sites/$siteId/pricing-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPerformanceHistoryRoute =
  AuthenticatedSitesSiteIdPerformanceHistoryRouteImport.update({
    id: '/sites/$siteId/performance-history',
    path: '/sites/$siteId/performance-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdModelCatalogRoute =
  AuthenticatedSitesSiteIdModelCatalogRouteImport.update({
    id: '/sites/$siteId/model-catalog',
    path: '/sites/$siteId/model-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdLogsRoute =
  AuthenticatedSitesSiteIdLogsRouteImport.update({
    id: '/sites/$siteId/logs',
    path: '/sites/$siteId/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdFinancialOperationsRoute =
  AuthenticatedSitesSiteIdFinancialOperationsRouteImport.update({
    id: '/sites/$siteId/financial-operations',
    path: '/sites/$siteId/financial-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdCollectionRunsRoute =
  AuthenticatedSitesSiteIdCollectionRunsRouteImport.update({
    id: '/sites/$siteId/collection-runs',
    path: '/sites/$siteId/collection-runs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdChannelInventoryRoute =
  AuthenticatedSitesSiteIdChannelInventoryRouteImport.update({
    id: '/sites/$siteId/channel-inventory',
    path: '/sites/$siteId/channel-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdStatsRoute =
  AuthenticatedCustomersCustomerIdStatsRouteImport.update({
    id: '/customers/$customerId/stats',
    path: '/customers/$customerId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdStatsRoute =
  AuthenticatedAccountsAccountIdStatsRouteImport.update({
    id: '/accounts/$accountId/stats',
    path: '/accounts/$accountId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/channel-inventory': typeof AuthenticatedChannelInventoryRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/financial-operations': typeof AuthenticatedFinancialOperationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/model-catalog': typeof AuthenticatedModelCatalogRoute
  '/performance-history': typeof AuthenticatedPerformanceHistoryRoute
  '/pricing-groups': typeof AuthenticatedPricingGroupsRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/system-tasks': typeof AuthenticatedSystemTasksRoute
  '/upstream-tasks': typeof AuthenticatedUpstreamTasksRoute
  '/user-inventory': typeof AuthenticatedUserInventoryRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/sites/$siteId/collection-runs': typeof AuthenticatedSitesSiteIdCollectionRunsRoute
  '/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/accounts/$accountId/': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/sites/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/channel-inventory': typeof AuthenticatedChannelInventoryRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/financial-operations': typeof AuthenticatedFinancialOperationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/model-catalog': typeof AuthenticatedModelCatalogRoute
  '/performance-history': typeof AuthenticatedPerformanceHistoryRoute
  '/pricing-groups': typeof AuthenticatedPricingGroupsRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/system-tasks': typeof AuthenticatedSystemTasksRoute
  '/upstream-tasks': typeof AuthenticatedUpstreamTasksRoute
  '/user-inventory': typeof AuthenticatedUserInventoryRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/sites/$siteId/collection-runs': typeof AuthenticatedSitesSiteIdCollectionRunsRoute
  '/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/accounts_': typeof AuthenticatedAccountsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/channel-inventory': typeof AuthenticatedChannelInventoryRoute
  '/_authenticated/customers_': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/financial-operations': typeof AuthenticatedFinancialOperationsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/model-catalog': typeof AuthenticatedModelCatalogRoute
  '/_authenticated/performance-history': typeof AuthenticatedPerformanceHistoryRoute
  '/_authenticated/pricing-groups': typeof AuthenticatedPricingGroupsRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/sites_': typeof AuthenticatedSitesRoute
  '/_authenticated/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/_authenticated/system-tasks': typeof AuthenticatedSystemTasksRoute
  '/_authenticated/upstream-tasks': typeof AuthenticatedUpstreamTasksRoute
  '/_authenticated/user-inventory': typeof AuthenticatedUserInventoryRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/_authenticated/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/_authenticated/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/_authenticated/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/_authenticated/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/_authenticated/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/_authenticated/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/_authenticated/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/_authenticated/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/_authenticated/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/_authenticated/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/_authenticated/sites/$siteId/collection-runs': typeof AuthenticatedSitesSiteIdCollectionRunsRoute
  '/_authenticated/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/_authenticated/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/_authenticated/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/_authenticated/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/_authenticated/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/_authenticated/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/_authenticated/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/_authenticated/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/_authenticated/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/_authenticated/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/_authenticated/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/_authenticated/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/_authenticated/accounts/$accountId/': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/_authenticated/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/_authenticated/sites/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/alerts'
    | '/change-password'
    | '/channel-inventory'
    | '/customers'
    | '/dashboard'
    | '/exports'
    | '/financial-operations'
    | '/logs'
    | '/model-catalog'
    | '/performance-history'
    | '/pricing-groups'
    | '/rankings'
    | '/sites'
    | '/subscription-plans'
    | '/system-tasks'
    | '/upstream-tasks'
    | '/user-inventory'
    | '/settings/system'
    | '/settings/users'
    | '/statistics/accounts'
    | '/statistics/channels'
    | '/statistics/customers'
    | '/statistics/global'
    | '/statistics/groups'
    | '/statistics/models'
    | '/statistics/nodes'
    | '/statistics/sites'
    | '/statistics/tokens'
    | '/settings/'
    | '/accounts/$accountId/stats'
    | '/customers/$customerId/stats'
    | '/sites/$siteId/channel-inventory'
    | '/sites/$siteId/collection-runs'
    | '/sites/$siteId/financial-operations'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/model-catalog'
    | '/sites/$siteId/performance-history'
    | '/sites/$siteId/pricing-groups'
    | '/sites/$siteId/rankings'
    | '/sites/$siteId/stats'
    | '/sites/$siteId/status'
    | '/sites/$siteId/subscription-plans'
    | '/sites/$siteId/system-tasks'
    | '/sites/$siteId/upstream-tasks'
    | '/sites/$siteId/user-inventory'
    | '/accounts/$accountId/'
    | '/customers/$customerId/'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/alerts'
    | '/change-password'
    | '/channel-inventory'
    | '/customers'
    | '/dashboard'
    | '/exports'
    | '/financial-operations'
    | '/logs'
    | '/model-catalog'
    | '/performance-history'
    | '/pricing-groups'
    | '/rankings'
    | '/sites'
    | '/subscription-plans'
    | '/system-tasks'
    | '/upstream-tasks'
    | '/user-inventory'
    | '/settings/system'
    | '/settings/users'
    | '/statistics/accounts'
    | '/statistics/channels'
    | '/statistics/customers'
    | '/statistics/global'
    | '/statistics/groups'
    | '/statistics/models'
    | '/statistics/nodes'
    | '/statistics/sites'
    | '/statistics/tokens'
    | '/settings'
    | '/accounts/$accountId/stats'
    | '/customers/$customerId/stats'
    | '/sites/$siteId/channel-inventory'
    | '/sites/$siteId/collection-runs'
    | '/sites/$siteId/financial-operations'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/model-catalog'
    | '/sites/$siteId/performance-history'
    | '/sites/$siteId/pricing-groups'
    | '/sites/$siteId/rankings'
    | '/sites/$siteId/stats'
    | '/sites/$siteId/status'
    | '/sites/$siteId/subscription-plans'
    | '/sites/$siteId/system-tasks'
    | '/sites/$siteId/upstream-tasks'
    | '/sites/$siteId/user-inventory'
    | '/accounts/$accountId'
    | '/customers/$customerId'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/accounts_'
    | '/_authenticated/alerts'
    | '/_authenticated/change-password'
    | '/_authenticated/channel-inventory'
    | '/_authenticated/customers_'
    | '/_authenticated/dashboard'
    | '/_authenticated/exports'
    | '/_authenticated/financial-operations'
    | '/_authenticated/logs'
    | '/_authenticated/model-catalog'
    | '/_authenticated/performance-history'
    | '/_authenticated/pricing-groups'
    | '/_authenticated/rankings'
    | '/_authenticated/sites_'
    | '/_authenticated/subscription-plans'
    | '/_authenticated/system-tasks'
    | '/_authenticated/upstream-tasks'
    | '/_authenticated/user-inventory'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/users'
    | '/_authenticated/statistics/accounts'
    | '/_authenticated/statistics/channels'
    | '/_authenticated/statistics/customers'
    | '/_authenticated/statistics/global'
    | '/_authenticated/statistics/groups'
    | '/_authenticated/statistics/models'
    | '/_authenticated/statistics/nodes'
    | '/_authenticated/statistics/sites'
    | '/_authenticated/statistics/tokens'
    | '/_authenticated/settings/'
    | '/_authenticated/accounts/$accountId/stats'
    | '/_authenticated/customers/$customerId/stats'
    | '/_authenticated/sites/$siteId/channel-inventory'
    | '/_authenticated/sites/$siteId/collection-runs'
    | '/_authenticated/sites/$siteId/financial-operations'
    | '/_authenticated/sites/$siteId/logs'
    | '/_authenticated/sites/$siteId/model-catalog'
    | '/_authenticated/sites/$siteId/performance-history'
    | '/_authenticated/sites/$siteId/pricing-groups'
    | '/_authenticated/sites/$siteId/rankings'
    | '/_authenticated/sites/$siteId/stats'
    | '/_authenticated/sites/$siteId/status'
    | '/_authenticated/sites/$siteId/subscription-plans'
    | '/_authenticated/sites/$siteId/system-tasks'
    | '/_authenticated/sites/$siteId/upstream-tasks'
    | '/_authenticated/sites/$siteId/user-inventory'
    | '/_authenticated/accounts/$accountId/'
    | '/_authenticated/customers/$customerId/'
    | '/_authenticated/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user-inventory': {
      id: '/_authenticated/user-inventory'
      path: '/user-inventory'
      fullPath: '/user-inventory'
      preLoaderRoute: typeof AuthenticatedUserInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upstream-tasks': {
      id: '/_authenticated/upstream-tasks'
      path: '/upstream-tasks'
      fullPath: '/upstream-tasks'
      preLoaderRoute: typeof AuthenticatedUpstreamTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-tasks': {
      id: '/_authenticated/system-tasks'
      path: '/system-tasks'
      fullPath: '/system-tasks'
      preLoaderRoute: typeof AuthenticatedSystemTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription-plans': {
      id: '/_authenticated/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof AuthenticatedSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites_': {
      id: '/_authenticated/sites_'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing-groups': {
      id: '/_authenticated/pricing-groups'
      path: '/pricing-groups'
      fullPath: '/pricing-groups'
      preLoaderRoute: typeof AuthenticatedPricingGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance-history': {
      id: '/_authenticated/performance-history'
      path: '/performance-history'
      fullPath: '/performance-history'
      preLoaderRoute: typeof AuthenticatedPerformanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-catalog': {
      id: '/_authenticated/model-catalog'
      path: '/model-catalog'
      fullPath: '/model-catalog'
      preLoaderRoute: typeof AuthenticatedModelCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial-operations': {
      id: '/_authenticated/financial-operations'
      path: '/financial-operations'
      fullPath: '/financial-operations'
      preLoaderRoute: typeof AuthenticatedFinancialOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers_': {
      id: '/_authenticated/customers_'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel-inventory': {
      id: '/_authenticated/channel-inventory'
      path: '/channel-inventory'
      fullPath: '/channel-inventory'
      preLoaderRoute: typeof AuthenticatedChannelInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts_': {
      id: '/_authenticated/accounts_'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/tokens': {
      id: '/_authenticated/statistics/tokens'
      path: '/statistics/tokens'
      fullPath: '/statistics/tokens'
      preLoaderRoute: typeof AuthenticatedStatisticsTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/sites': {
      id: '/_authenticated/statistics/sites'
      path: '/statistics/sites'
      fullPath: '/statistics/sites'
      preLoaderRoute: typeof AuthenticatedStatisticsSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/nodes': {
      id: '/_authenticated/statistics/nodes'
      path: '/statistics/nodes'
      fullPath: '/statistics/nodes'
      preLoaderRoute: typeof AuthenticatedStatisticsNodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/models': {
      id: '/_authenticated/statistics/models'
      path: '/statistics/models'
      fullPath: '/statistics/models'
      preLoaderRoute: typeof AuthenticatedStatisticsModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/groups': {
      id: '/_authenticated/statistics/groups'
      path: '/statistics/groups'
      fullPath: '/statistics/groups'
      preLoaderRoute: typeof AuthenticatedStatisticsGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/global': {
      id: '/_authenticated/statistics/global'
      path: '/statistics/global'
      fullPath: '/statistics/global'
      preLoaderRoute: typeof AuthenticatedStatisticsGlobalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/customers': {
      id: '/_authenticated/statistics/customers'
      path: '/statistics/customers'
      fullPath: '/statistics/customers'
      preLoaderRoute: typeof AuthenticatedStatisticsCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/channels': {
      id: '/_authenticated/statistics/channels'
      path: '/statistics/channels'
      fullPath: '/statistics/channels'
      preLoaderRoute: typeof AuthenticatedStatisticsChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/accounts': {
      id: '/_authenticated/statistics/accounts'
      path: '/statistics/accounts'
      fullPath: '/statistics/accounts'
      preLoaderRoute: typeof AuthenticatedStatisticsAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/': {
      id: '/_authenticated/sites/$siteId/'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/': {
      id: '/_authenticated/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId/': {
      id: '/_authenticated/accounts/$accountId/'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/user-inventory': {
      id: '/_authenticated/sites/$siteId/user-inventory'
      path: '/sites/$siteId/user-inventory'
      fullPath: '/sites/$siteId/user-inventory'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdUserInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/upstream-tasks': {
      id: '/_authenticated/sites/$siteId/upstream-tasks'
      path: '/sites/$siteId/upstream-tasks'
      fullPath: '/sites/$siteId/upstream-tasks'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdUpstreamTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/system-tasks': {
      id: '/_authenticated/sites/$siteId/system-tasks'
      path: '/sites/$siteId/system-tasks'
      fullPath: '/sites/$siteId/system-tasks'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdSystemTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/subscription-plans': {
      id: '/_authenticated/sites/$siteId/subscription-plans'
      path: '/sites/$siteId/subscription-plans'
      fullPath: '/sites/$siteId/subscription-plans'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/status': {
      id: '/_authenticated/sites/$siteId/status'
      path: '/sites/$siteId/status'
      fullPath: '/sites/$siteId/status'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/stats': {
      id: '/_authenticated/sites/$siteId/stats'
      path: '/sites/$siteId/stats'
      fullPath: '/sites/$siteId/stats'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/rankings': {
      id: '/_authenticated/sites/$siteId/rankings'
      path: '/sites/$siteId/rankings'
      fullPath: '/sites/$siteId/rankings'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/pricing-groups': {
      id: '/_authenticated/sites/$siteId/pricing-groups'
      path: '/sites/$siteId/pricing-groups'
      fullPath: '/sites/$siteId/pricing-groups'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPricingGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/performance-history': {
      id: '/_authenticated/sites/$siteId/performance-history'
      path: '/sites/$siteId/performance-history'
      fullPath: '/sites/$siteId/performance-history'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPerformanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/model-catalog': {
      id: '/_authenticated/sites/$siteId/model-catalog'
      path: '/sites/$siteId/model-catalog'
      fullPath: '/sites/$siteId/model-catalog'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdModelCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/logs': {
      id: '/_authenticated/sites/$siteId/logs'
      path: '/sites/$siteId/logs'
      fullPath: '/sites/$siteId/logs'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/financial-operations': {
      id: '/_authenticated/sites/$siteId/financial-operations'
      path: '/sites/$siteId/financial-operations'
      fullPath: '/sites/$siteId/financial-operations'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdFinancialOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/collection-runs': {
      id: '/_authenticated/sites/$siteId/collection-runs'
      path: '/sites/$siteId/collection-runs'
      fullPath: '/sites/$siteId/collection-runs'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdCollectionRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/channel-inventory': {
      id: '/_authenticated/sites/$siteId/channel-inventory'
      path: '/sites/$siteId/channel-inventory'
      fullPath: '/sites/$siteId/channel-inventory'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdChannelInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/stats': {
      id: '/_authenticated/customers/$customerId/stats'
      path: '/customers/$customerId/stats'
      fullPath: '/customers/$customerId/stats'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId/stats': {
      id: '/_authenticated/accounts/$accountId/stats'
      path: '/accounts/$accountId/stats'
      fullPath: '/accounts/$accountId/stats'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedChannelInventoryRoute: typeof AuthenticatedChannelInventoryRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedFinancialOperationsRoute: typeof AuthenticatedFinancialOperationsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModelCatalogRoute: typeof AuthenticatedModelCatalogRoute
  AuthenticatedPerformanceHistoryRoute: typeof AuthenticatedPerformanceHistoryRoute
  AuthenticatedPricingGroupsRoute: typeof AuthenticatedPricingGroupsRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedSubscriptionPlansRoute: typeof AuthenticatedSubscriptionPlansRoute
  AuthenticatedSystemTasksRoute: typeof AuthenticatedSystemTasksRoute
  AuthenticatedUpstreamTasksRoute: typeof AuthenticatedUpstreamTasksRoute
  AuthenticatedUserInventoryRoute: typeof AuthenticatedUserInventoryRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedStatisticsAccountsRoute: typeof AuthenticatedStatisticsAccountsRoute
  AuthenticatedStatisticsChannelsRoute: typeof AuthenticatedStatisticsChannelsRoute
  AuthenticatedStatisticsCustomersRoute: typeof AuthenticatedStatisticsCustomersRoute
  AuthenticatedStatisticsGlobalRoute: typeof AuthenticatedStatisticsGlobalRoute
  AuthenticatedStatisticsGroupsRoute: typeof AuthenticatedStatisticsGroupsRoute
  AuthenticatedStatisticsModelsRoute: typeof AuthenticatedStatisticsModelsRoute
  AuthenticatedStatisticsNodesRoute: typeof AuthenticatedStatisticsNodesRoute
  AuthenticatedStatisticsSitesRoute: typeof AuthenticatedStatisticsSitesRoute
  AuthenticatedStatisticsTokensRoute: typeof AuthenticatedStatisticsTokensRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedAccountsAccountIdStatsRoute: typeof AuthenticatedAccountsAccountIdStatsRoute
  AuthenticatedCustomersCustomerIdStatsRoute: typeof AuthenticatedCustomersCustomerIdStatsRoute
  AuthenticatedSitesSiteIdChannelInventoryRoute: typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  AuthenticatedSitesSiteIdCollectionRunsRoute: typeof AuthenticatedSitesSiteIdCollectionRunsRoute
  AuthenticatedSitesSiteIdFinancialOperationsRoute: typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  AuthenticatedSitesSiteIdLogsRoute: typeof AuthenticatedSitesSiteIdLogsRoute
  AuthenticatedSitesSiteIdModelCatalogRoute: typeof AuthenticatedSitesSiteIdModelCatalogRoute
  AuthenticatedSitesSiteIdPerformanceHistoryRoute: typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  AuthenticatedSitesSiteIdPricingGroupsRoute: typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  AuthenticatedSitesSiteIdRankingsRoute: typeof AuthenticatedSitesSiteIdRankingsRoute
  AuthenticatedSitesSiteIdStatsRoute: typeof AuthenticatedSitesSiteIdStatsRoute
  AuthenticatedSitesSiteIdStatusRoute: typeof AuthenticatedSitesSiteIdStatusRoute
  AuthenticatedSitesSiteIdSubscriptionPlansRoute: typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  AuthenticatedSitesSiteIdSystemTasksRoute: typeof AuthenticatedSitesSiteIdSystemTasksRoute
  AuthenticatedSitesSiteIdUpstreamTasksRoute: typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  AuthenticatedSitesSiteIdUserInventoryRoute: typeof AuthenticatedSitesSiteIdUserInventoryRoute
  AuthenticatedAccountsAccountIdIndexRoute: typeof AuthenticatedAccountsAccountIdIndexRoute
  AuthenticatedCustomersCustomerIdIndexRoute: typeof AuthenticatedCustomersCustomerIdIndexRoute
  AuthenticatedSitesSiteIdIndexRoute: typeof AuthenticatedSitesSiteIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedChannelInventoryRoute: AuthenticatedChannelInventoryRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedFinancialOperationsRoute: AuthenticatedFinancialOperationsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelCatalogRoute: AuthenticatedModelCatalogRoute,
  AuthenticatedPerformanceHistoryRoute: AuthenticatedPerformanceHistoryRoute,
  AuthenticatedPricingGroupsRoute: AuthenticatedPricingGroupsRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedSubscriptionPlansRoute: AuthenticatedSubscriptionPlansRoute,
  AuthenticatedSystemTasksRoute: AuthenticatedSystemTasksRoute,
  AuthenticatedUpstreamTasksRoute: AuthenticatedUpstreamTasksRoute,
  AuthenticatedUserInventoryRoute: AuthenticatedUserInventoryRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedStatisticsAccountsRoute: AuthenticatedStatisticsAccountsRoute,
  AuthenticatedStatisticsChannelsRoute: AuthenticatedStatisticsChannelsRoute,
  AuthenticatedStatisticsCustomersRoute: AuthenticatedStatisticsCustomersRoute,
  AuthenticatedStatisticsGlobalRoute: AuthenticatedStatisticsGlobalRoute,
  AuthenticatedStatisticsGroupsRoute: AuthenticatedStatisticsGroupsRoute,
  AuthenticatedStatisticsModelsRoute: AuthenticatedStatisticsModelsRoute,
  AuthenticatedStatisticsNodesRoute: AuthenticatedStatisticsNodesRoute,
  AuthenticatedStatisticsSitesRoute: AuthenticatedStatisticsSitesRoute,
  AuthenticatedStatisticsTokensRoute: AuthenticatedStatisticsTokensRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedAccountsAccountIdStatsRoute:
    AuthenticatedAccountsAccountIdStatsRoute,
  AuthenticatedCustomersCustomerIdStatsRoute:
    AuthenticatedCustomersCustomerIdStatsRoute,
  AuthenticatedSitesSiteIdChannelInventoryRoute:
    AuthenticatedSitesSiteIdChannelInventoryRoute,
  AuthenticatedSitesSiteIdCollectionRunsRoute:
    AuthenticatedSitesSiteIdCollectionRunsRoute,
  AuthenticatedSitesSiteIdFinancialOperationsRoute:
    AuthenticatedSitesSiteIdFinancialOperationsRoute,
  AuthenticatedSitesSiteIdLogsRoute: AuthenticatedSitesSiteIdLogsRoute,
  AuthenticatedSitesSiteIdModelCatalogRoute:
    AuthenticatedSitesSiteIdModelCatalogRoute,
  AuthenticatedSitesSiteIdPerformanceHistoryRoute:
    AuthenticatedSitesSiteIdPerformanceHistoryRoute,
  AuthenticatedSitesSiteIdPricingGroupsRoute:
    AuthenticatedSitesSiteIdPricingGroupsRoute,
  AuthenticatedSitesSiteIdRankingsRoute: AuthenticatedSitesSiteIdRankingsRoute,
  AuthenticatedSitesSiteIdStatsRoute: AuthenticatedSitesSiteIdStatsRoute,
  AuthenticatedSitesSiteIdStatusRoute: AuthenticatedSitesSiteIdStatusRoute,
  AuthenticatedSitesSiteIdSubscriptionPlansRoute:
    AuthenticatedSitesSiteIdSubscriptionPlansRoute,
  AuthenticatedSitesSiteIdSystemTasksRoute:
    AuthenticatedSitesSiteIdSystemTasksRoute,
  AuthenticatedSitesSiteIdUpstreamTasksRoute:
    AuthenticatedSitesSiteIdUpstreamTasksRoute,
  AuthenticatedSitesSiteIdUserInventoryRoute:
    AuthenticatedSitesSiteIdUserInventoryRoute,
  AuthenticatedAccountsAccountIdIndexRoute:
    AuthenticatedAccountsAccountIdIndexRoute,
  AuthenticatedCustomersCustomerIdIndexRoute:
    AuthenticatedCustomersCustomerIdIndexRoute,
  AuthenticatedSitesSiteIdIndexRoute: AuthenticatedSitesSiteIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
