/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUserInventoryIndexRouteImport } from './routes/_authenticated/user-inventory/index'
import { Route as AuthenticatedUpstreamTasksIndexRouteImport } from './routes/_authenticated/upstream-tasks/index'
import { Route as AuthenticatedSystemTasksIndexRouteImport } from './routes/_authenticated/system-tasks/index'
import { Route as AuthenticatedSubscriptionPlansIndexRouteImport } from './routes/_authenticated/subscription-plans/index'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRankingsIndexRouteImport } from './routes/_authenticated/rankings/index'
import { Route as AuthenticatedPricingGroupsIndexRouteImport } from './routes/_authenticated/pricing-groups/index'
import { Route as AuthenticatedPerformanceHistoryIndexRouteImport } from './routes/_authenticated/performance-history/index'
import { Route as AuthenticatedModelCatalogIndexRouteImport } from './routes/_authenticated/model-catalog/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedFinancialOperationsIndexRouteImport } from './routes/_authenticated/financial-operations/index'
import { Route as AuthenticatedExportsIndexRouteImport } from './routes/_authenticated/exports/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedChannelInventoryIndexRouteImport } from './routes/_authenticated/channel-inventory/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedStatisticsTokensRouteImport } from './routes/_authenticated/statistics/tokens'
import { Route as AuthenticatedStatisticsSitesRouteImport } from './routes/_authenticated/statistics/sites'
import { Route as AuthenticatedStatisticsNodesRouteImport } from './routes/_authenticated/statistics/nodes'
import { Route as AuthenticatedStatisticsModelsRouteImport } from './routes/_authenticated/statistics/models'
import { Route as AuthenticatedStatisticsGroupsRouteImport } from './routes/_authenticated/statistics/groups'
import { Route as AuthenticatedStatisticsGlobalRouteImport } from './routes/_authenticated/statistics/global'
import { Route as AuthenticatedStatisticsCustomersRouteImport } from './routes/_authenticated/statistics/customers'
import { Route as AuthenticatedStatisticsChannelsRouteImport } from './routes/_authenticated/statistics/channels'
import { Route as AuthenticatedStatisticsAccountsRouteImport } from './routes/_authenticated/statistics/accounts'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSitesSiteIdIndexRouteImport } from './routes/_authenticated/sites/$siteId/index'
import { Route as AuthenticatedCustomersCustomerIdIndexRouteImport } from './routes/_authenticated/customers/$customerId/index'
import { Route as AuthenticatedAccountsAccountIdIndexRouteImport } from './routes/_authenticated/accounts/$accountId/index'
import { Route as AuthenticatedSitesSiteIdUserInventoryRouteImport } from './routes/_authenticated/sites/$siteId/user-inventory'
import { Route as AuthenticatedSitesSiteIdUpstreamTasksRouteImport } from './routes/_authenticated/sites/$siteId/upstream-tasks'
import { Route as AuthenticatedSitesSiteIdSystemTasksRouteImport } from './routes/_authenticated/sites/$siteId/system-tasks'
import { Route as AuthenticatedSitesSiteIdSubscriptionPlansRouteImport } from './routes/_authenticated/sites/$siteId/subscription-plans'
import { Route as AuthenticatedSitesSiteIdStatusRouteImport } from './routes/_authenticated/sites/$siteId/status'
import { Route as AuthenticatedSitesSiteIdStatsRouteImport } from './routes/_authenticated/sites/$siteId/stats'
import { Route as AuthenticatedSitesSiteIdRankingsRouteImport } from './routes/_authenticated/sites/$siteId/rankings'
import { Route as AuthenticatedSitesSiteIdPricingGroupsRouteImport } from './routes/_authenticated/sites/$siteId/pricing-groups'
import { Route as AuthenticatedSitesSiteIdPerformanceHistoryRouteImport } from './routes/_authenticated/sites/$siteId/performance-history'
import { Route as AuthenticatedSitesSiteIdModelCatalogRouteImport } from './routes/_authenticated/sites/$siteId/model-catalog'
import { Route as AuthenticatedSitesSiteIdLogsRouteImport } from './routes/_authenticated/sites/$siteId/logs'
import { Route as AuthenticatedSitesSiteIdFinancialOperationsRouteImport } from './routes/_authenticated/sites/$siteId/financial-operations'
import { Route as AuthenticatedSitesSiteIdChannelInventoryRouteImport } from './routes/_authenticated/sites/$siteId/channel-inventory'
import { Route as AuthenticatedCustomersCustomerIdStatsRouteImport } from './routes/_authenticated/customers/$customerId/stats'
import { Route as AuthenticatedAccountsAccountIdStatsRouteImport } from './routes/_authenticated/accounts/$accountId/stats'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserInventoryIndexRoute =
  AuthenticatedUserInventoryIndexRouteImport.update({
    id: '/user-inventory/',
    path: '/user-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUpstreamTasksIndexRoute =
  AuthenticatedUpstreamTasksIndexRouteImport.update({
    id: '/upstream-tasks/',
    path: '/upstream-tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemTasksIndexRoute =
  AuthenticatedSystemTasksIndexRouteImport.update({
    id: '/system-tasks/',
    path: '/system-tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionPlansIndexRoute =
  AuthenticatedSubscriptionPlansIndexRouteImport.update({
    id: '/subscription-plans/',
    path: '/subscription-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingsIndexRoute =
  AuthenticatedRankingsIndexRouteImport.update({
    id: '/rankings/',
    path: '/rankings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPricingGroupsIndexRoute =
  AuthenticatedPricingGroupsIndexRouteImport.update({
    id: '/pricing-groups/',
    path: '/pricing-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceHistoryIndexRoute =
  AuthenticatedPerformanceHistoryIndexRouteImport.update({
    id: '/performance-history/',
    path: '/performance-history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelCatalogIndexRoute =
  AuthenticatedModelCatalogIndexRouteImport.update({
    id: '/model-catalog/',
    path: '/model-catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialOperationsIndexRoute =
  AuthenticatedFinancialOperationsIndexRouteImport.update({
    id: '/financial-operations/',
    path: '/financial-operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportsIndexRoute =
  AuthenticatedExportsIndexRouteImport.update({
    id: '/exports/',
    path: '/exports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChannelInventoryIndexRoute =
  AuthenticatedChannelInventoryIndexRouteImport.update({
    id: '/channel-inventory/',
    path: '/channel-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsTokensRoute =
  AuthenticatedStatisticsTokensRouteImport.update({
    id: '/statistics/tokens',
    path: '/statistics/tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsSitesRoute =
  AuthenticatedStatisticsSitesRouteImport.update({
    id: '/statistics/sites',
    path: '/statistics/sites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsNodesRoute =
  AuthenticatedStatisticsNodesRouteImport.update({
    id: '/statistics/nodes',
    path: '/statistics/nodes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsModelsRoute =
  AuthenticatedStatisticsModelsRouteImport.update({
    id: '/statistics/models',
    path: '/statistics/models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsGroupsRoute =
  AuthenticatedStatisticsGroupsRouteImport.update({
    id: '/statistics/groups',
    path: '/statistics/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsGlobalRoute =
  AuthenticatedStatisticsGlobalRouteImport.update({
    id: '/statistics/global',
    path: '/statistics/global',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsCustomersRoute =
  AuthenticatedStatisticsCustomersRouteImport.update({
    id: '/statistics/customers',
    path: '/statistics/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsChannelsRoute =
  AuthenticatedStatisticsChannelsRouteImport.update({
    id: '/statistics/channels',
    path: '/statistics/channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsAccountsRoute =
  AuthenticatedStatisticsAccountsRouteImport.update({
    id: '/statistics/accounts',
    path: '/statistics/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdIndexRoute =
  AuthenticatedSitesSiteIdIndexRouteImport.update({
    id: '/sites/$siteId/',
    path: '/sites/$siteId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdIndexRoute =
  AuthenticatedCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdIndexRoute =
  AuthenticatedAccountsAccountIdIndexRouteImport.update({
    id: '/accounts/$accountId/',
    path: '/accounts/$accountId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdUserInventoryRoute =
  AuthenticatedSitesSiteIdUserInventoryRouteImport.update({
    id: '/sites/$siteId/user-inventory',
    path: '/sites/$siteId/user-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdUpstreamTasksRoute =
  AuthenticatedSitesSiteIdUpstreamTasksRouteImport.update({
    id: '/sites/$siteId/upstream-tasks',
    path: '/sites/$siteId/upstream-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdSystemTasksRoute =
  AuthenticatedSitesSiteIdSystemTasksRouteImport.update({
    id: '/sites/$siteId/system-tasks',
    path: '/sites/$siteId/system-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdSubscriptionPlansRoute =
  AuthenticatedSitesSiteIdSubscriptionPlansRouteImport.update({
    id: '/sites/$siteId/subscription-plans',
    path: '/sites/$siteId/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdStatusRoute =
  AuthenticatedSitesSiteIdStatusRouteImport.update({
    id: '/sites/$siteId/status',
    path: '/sites/$siteId/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdStatsRoute =
  AuthenticatedSitesSiteIdStatsRouteImport.update({
    id: '/sites/$siteId/stats',
    path: '/sites/$siteId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdRankingsRoute =
  AuthenticatedSitesSiteIdRankingsRouteImport.update({
    id: '/sites/$siteId/rankings',
    path: '/sites/$siteId/rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPricingGroupsRoute =
  AuthenticatedSitesSiteIdPricingGroupsRouteImport.update({
    id: '/sites/$siteId/pricing-groups',
    path: '/sites/$siteId/pricing-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPerformanceHistoryRoute =
  AuthenticatedSitesSiteIdPerformanceHistoryRouteImport.update({
    id: '/sites/$siteId/performance-history',
    path: '/sites/$siteId/performance-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdModelCatalogRoute =
  AuthenticatedSitesSiteIdModelCatalogRouteImport.update({
    id: '/sites/$siteId/model-catalog',
    path: '/sites/$siteId/model-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdLogsRoute =
  AuthenticatedSitesSiteIdLogsRouteImport.update({
    id: '/sites/$siteId/logs',
    path: '/sites/$siteId/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdFinancialOperationsRoute =
  AuthenticatedSitesSiteIdFinancialOperationsRouteImport.update({
    id: '/sites/$siteId/financial-operations',
    path: '/sites/$siteId/financial-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdChannelInventoryRoute =
  AuthenticatedSitesSiteIdChannelInventoryRouteImport.update({
    id: '/sites/$siteId/channel-inventory',
    path: '/sites/$siteId/channel-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdStatsRoute =
  AuthenticatedCustomersCustomerIdStatsRouteImport.update({
    id: '/customers/$customerId/stats',
    path: '/customers/$customerId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdStatsRoute =
  AuthenticatedAccountsAccountIdStatsRouteImport.update({
    id: '/accounts/$accountId/stats',
    path: '/accounts/$accountId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/channel-inventory/': typeof AuthenticatedChannelInventoryIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/exports/': typeof AuthenticatedExportsIndexRoute
  '/financial-operations/': typeof AuthenticatedFinancialOperationsIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/model-catalog/': typeof AuthenticatedModelCatalogIndexRoute
  '/performance-history/': typeof AuthenticatedPerformanceHistoryIndexRoute
  '/pricing-groups/': typeof AuthenticatedPricingGroupsIndexRoute
  '/rankings/': typeof AuthenticatedRankingsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/subscription-plans/': typeof AuthenticatedSubscriptionPlansIndexRoute
  '/system-tasks/': typeof AuthenticatedSystemTasksIndexRoute
  '/upstream-tasks/': typeof AuthenticatedUpstreamTasksIndexRoute
  '/user-inventory/': typeof AuthenticatedUserInventoryIndexRoute
  '/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/accounts/$accountId/': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/sites/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/channel-inventory': typeof AuthenticatedChannelInventoryIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/exports': typeof AuthenticatedExportsIndexRoute
  '/financial-operations': typeof AuthenticatedFinancialOperationsIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/model-catalog': typeof AuthenticatedModelCatalogIndexRoute
  '/performance-history': typeof AuthenticatedPerformanceHistoryIndexRoute
  '/pricing-groups': typeof AuthenticatedPricingGroupsIndexRoute
  '/rankings': typeof AuthenticatedRankingsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansIndexRoute
  '/system-tasks': typeof AuthenticatedSystemTasksIndexRoute
  '/upstream-tasks': typeof AuthenticatedUpstreamTasksIndexRoute
  '/user-inventory': typeof AuthenticatedUserInventoryIndexRoute
  '/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/statistics/accounts': typeof AuthenticatedStatisticsAccountsRoute
  '/_authenticated/statistics/channels': typeof AuthenticatedStatisticsChannelsRoute
  '/_authenticated/statistics/customers': typeof AuthenticatedStatisticsCustomersRoute
  '/_authenticated/statistics/global': typeof AuthenticatedStatisticsGlobalRoute
  '/_authenticated/statistics/groups': typeof AuthenticatedStatisticsGroupsRoute
  '/_authenticated/statistics/models': typeof AuthenticatedStatisticsModelsRoute
  '/_authenticated/statistics/nodes': typeof AuthenticatedStatisticsNodesRoute
  '/_authenticated/statistics/sites': typeof AuthenticatedStatisticsSitesRoute
  '/_authenticated/statistics/tokens': typeof AuthenticatedStatisticsTokensRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/channel-inventory/': typeof AuthenticatedChannelInventoryIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/exports/': typeof AuthenticatedExportsIndexRoute
  '/_authenticated/financial-operations/': typeof AuthenticatedFinancialOperationsIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/model-catalog/': typeof AuthenticatedModelCatalogIndexRoute
  '/_authenticated/performance-history/': typeof AuthenticatedPerformanceHistoryIndexRoute
  '/_authenticated/pricing-groups/': typeof AuthenticatedPricingGroupsIndexRoute
  '/_authenticated/rankings/': typeof AuthenticatedRankingsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/subscription-plans/': typeof AuthenticatedSubscriptionPlansIndexRoute
  '/_authenticated/system-tasks/': typeof AuthenticatedSystemTasksIndexRoute
  '/_authenticated/upstream-tasks/': typeof AuthenticatedUpstreamTasksIndexRoute
  '/_authenticated/user-inventory/': typeof AuthenticatedUserInventoryIndexRoute
  '/_authenticated/accounts/$accountId/stats': typeof AuthenticatedAccountsAccountIdStatsRoute
  '/_authenticated/customers/$customerId/stats': typeof AuthenticatedCustomersCustomerIdStatsRoute
  '/_authenticated/sites/$siteId/channel-inventory': typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  '/_authenticated/sites/$siteId/financial-operations': typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  '/_authenticated/sites/$siteId/logs': typeof AuthenticatedSitesSiteIdLogsRoute
  '/_authenticated/sites/$siteId/model-catalog': typeof AuthenticatedSitesSiteIdModelCatalogRoute
  '/_authenticated/sites/$siteId/performance-history': typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  '/_authenticated/sites/$siteId/pricing-groups': typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  '/_authenticated/sites/$siteId/rankings': typeof AuthenticatedSitesSiteIdRankingsRoute
  '/_authenticated/sites/$siteId/stats': typeof AuthenticatedSitesSiteIdStatsRoute
  '/_authenticated/sites/$siteId/status': typeof AuthenticatedSitesSiteIdStatusRoute
  '/_authenticated/sites/$siteId/subscription-plans': typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  '/_authenticated/sites/$siteId/system-tasks': typeof AuthenticatedSitesSiteIdSystemTasksRoute
  '/_authenticated/sites/$siteId/upstream-tasks': typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  '/_authenticated/sites/$siteId/user-inventory': typeof AuthenticatedSitesSiteIdUserInventoryRoute
  '/_authenticated/accounts/$accountId/': typeof AuthenticatedAccountsAccountIdIndexRoute
  '/_authenticated/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/_authenticated/sites/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/change-password'
    | '/settings/system'
    | '/settings/users'
    | '/statistics/accounts'
    | '/statistics/channels'
    | '/statistics/customers'
    | '/statistics/global'
    | '/statistics/groups'
    | '/statistics/models'
    | '/statistics/nodes'
    | '/statistics/sites'
    | '/statistics/tokens'
    | '/accounts/'
    | '/alerts/'
    | '/channel-inventory/'
    | '/customers/'
    | '/dashboard/'
    | '/exports/'
    | '/financial-operations/'
    | '/logs/'
    | '/model-catalog/'
    | '/performance-history/'
    | '/pricing-groups/'
    | '/rankings/'
    | '/settings/'
    | '/sites/'
    | '/subscription-plans/'
    | '/system-tasks/'
    | '/upstream-tasks/'
    | '/user-inventory/'
    | '/accounts/$accountId/stats'
    | '/customers/$customerId/stats'
    | '/sites/$siteId/channel-inventory'
    | '/sites/$siteId/financial-operations'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/model-catalog'
    | '/sites/$siteId/performance-history'
    | '/sites/$siteId/pricing-groups'
    | '/sites/$siteId/rankings'
    | '/sites/$siteId/stats'
    | '/sites/$siteId/status'
    | '/sites/$siteId/subscription-plans'
    | '/sites/$siteId/system-tasks'
    | '/sites/$siteId/upstream-tasks'
    | '/sites/$siteId/user-inventory'
    | '/accounts/$accountId/'
    | '/customers/$customerId/'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/change-password'
    | '/settings/system'
    | '/settings/users'
    | '/statistics/accounts'
    | '/statistics/channels'
    | '/statistics/customers'
    | '/statistics/global'
    | '/statistics/groups'
    | '/statistics/models'
    | '/statistics/nodes'
    | '/statistics/sites'
    | '/statistics/tokens'
    | '/accounts'
    | '/alerts'
    | '/channel-inventory'
    | '/customers'
    | '/dashboard'
    | '/exports'
    | '/financial-operations'
    | '/logs'
    | '/model-catalog'
    | '/performance-history'
    | '/pricing-groups'
    | '/rankings'
    | '/settings'
    | '/sites'
    | '/subscription-plans'
    | '/system-tasks'
    | '/upstream-tasks'
    | '/user-inventory'
    | '/accounts/$accountId/stats'
    | '/customers/$customerId/stats'
    | '/sites/$siteId/channel-inventory'
    | '/sites/$siteId/financial-operations'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/model-catalog'
    | '/sites/$siteId/performance-history'
    | '/sites/$siteId/pricing-groups'
    | '/sites/$siteId/rankings'
    | '/sites/$siteId/stats'
    | '/sites/$siteId/status'
    | '/sites/$siteId/subscription-plans'
    | '/sites/$siteId/system-tasks'
    | '/sites/$siteId/upstream-tasks'
    | '/sites/$siteId/user-inventory'
    | '/accounts/$accountId'
    | '/customers/$customerId'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/change-password'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/users'
    | '/_authenticated/statistics/accounts'
    | '/_authenticated/statistics/channels'
    | '/_authenticated/statistics/customers'
    | '/_authenticated/statistics/global'
    | '/_authenticated/statistics/groups'
    | '/_authenticated/statistics/models'
    | '/_authenticated/statistics/nodes'
    | '/_authenticated/statistics/sites'
    | '/_authenticated/statistics/tokens'
    | '/_authenticated/accounts/'
    | '/_authenticated/alerts/'
    | '/_authenticated/channel-inventory/'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/exports/'
    | '/_authenticated/financial-operations/'
    | '/_authenticated/logs/'
    | '/_authenticated/model-catalog/'
    | '/_authenticated/performance-history/'
    | '/_authenticated/pricing-groups/'
    | '/_authenticated/rankings/'
    | '/_authenticated/settings/'
    | '/_authenticated/sites/'
    | '/_authenticated/subscription-plans/'
    | '/_authenticated/system-tasks/'
    | '/_authenticated/upstream-tasks/'
    | '/_authenticated/user-inventory/'
    | '/_authenticated/accounts/$accountId/stats'
    | '/_authenticated/customers/$customerId/stats'
    | '/_authenticated/sites/$siteId/channel-inventory'
    | '/_authenticated/sites/$siteId/financial-operations'
    | '/_authenticated/sites/$siteId/logs'
    | '/_authenticated/sites/$siteId/model-catalog'
    | '/_authenticated/sites/$siteId/performance-history'
    | '/_authenticated/sites/$siteId/pricing-groups'
    | '/_authenticated/sites/$siteId/rankings'
    | '/_authenticated/sites/$siteId/stats'
    | '/_authenticated/sites/$siteId/status'
    | '/_authenticated/sites/$siteId/subscription-plans'
    | '/_authenticated/sites/$siteId/system-tasks'
    | '/_authenticated/sites/$siteId/upstream-tasks'
    | '/_authenticated/sites/$siteId/user-inventory'
    | '/_authenticated/accounts/$accountId/'
    | '/_authenticated/customers/$customerId/'
    | '/_authenticated/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user-inventory/': {
      id: '/_authenticated/user-inventory/'
      path: '/user-inventory'
      fullPath: '/user-inventory/'
      preLoaderRoute: typeof AuthenticatedUserInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upstream-tasks/': {
      id: '/_authenticated/upstream-tasks/'
      path: '/upstream-tasks'
      fullPath: '/upstream-tasks/'
      preLoaderRoute: typeof AuthenticatedUpstreamTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-tasks/': {
      id: '/_authenticated/system-tasks/'
      path: '/system-tasks'
      fullPath: '/system-tasks/'
      preLoaderRoute: typeof AuthenticatedSystemTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription-plans/': {
      id: '/_authenticated/subscription-plans/'
      path: '/subscription-plans'
      fullPath: '/subscription-plans/'
      preLoaderRoute: typeof AuthenticatedSubscriptionPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings/': {
      id: '/_authenticated/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof AuthenticatedRankingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing-groups/': {
      id: '/_authenticated/pricing-groups/'
      path: '/pricing-groups'
      fullPath: '/pricing-groups/'
      preLoaderRoute: typeof AuthenticatedPricingGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance-history/': {
      id: '/_authenticated/performance-history/'
      path: '/performance-history'
      fullPath: '/performance-history/'
      preLoaderRoute: typeof AuthenticatedPerformanceHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-catalog/': {
      id: '/_authenticated/model-catalog/'
      path: '/model-catalog'
      fullPath: '/model-catalog/'
      preLoaderRoute: typeof AuthenticatedModelCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial-operations/': {
      id: '/_authenticated/financial-operations/'
      path: '/financial-operations'
      fullPath: '/financial-operations/'
      preLoaderRoute: typeof AuthenticatedFinancialOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exports/': {
      id: '/_authenticated/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof AuthenticatedExportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel-inventory/': {
      id: '/_authenticated/channel-inventory/'
      path: '/channel-inventory'
      fullPath: '/channel-inventory/'
      preLoaderRoute: typeof AuthenticatedChannelInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/tokens': {
      id: '/_authenticated/statistics/tokens'
      path: '/statistics/tokens'
      fullPath: '/statistics/tokens'
      preLoaderRoute: typeof AuthenticatedStatisticsTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/sites': {
      id: '/_authenticated/statistics/sites'
      path: '/statistics/sites'
      fullPath: '/statistics/sites'
      preLoaderRoute: typeof AuthenticatedStatisticsSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/nodes': {
      id: '/_authenticated/statistics/nodes'
      path: '/statistics/nodes'
      fullPath: '/statistics/nodes'
      preLoaderRoute: typeof AuthenticatedStatisticsNodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/models': {
      id: '/_authenticated/statistics/models'
      path: '/statistics/models'
      fullPath: '/statistics/models'
      preLoaderRoute: typeof AuthenticatedStatisticsModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/groups': {
      id: '/_authenticated/statistics/groups'
      path: '/statistics/groups'
      fullPath: '/statistics/groups'
      preLoaderRoute: typeof AuthenticatedStatisticsGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/global': {
      id: '/_authenticated/statistics/global'
      path: '/statistics/global'
      fullPath: '/statistics/global'
      preLoaderRoute: typeof AuthenticatedStatisticsGlobalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/customers': {
      id: '/_authenticated/statistics/customers'
      path: '/statistics/customers'
      fullPath: '/statistics/customers'
      preLoaderRoute: typeof AuthenticatedStatisticsCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/channels': {
      id: '/_authenticated/statistics/channels'
      path: '/statistics/channels'
      fullPath: '/statistics/channels'
      preLoaderRoute: typeof AuthenticatedStatisticsChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/accounts': {
      id: '/_authenticated/statistics/accounts'
      path: '/statistics/accounts'
      fullPath: '/statistics/accounts'
      preLoaderRoute: typeof AuthenticatedStatisticsAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/': {
      id: '/_authenticated/sites/$siteId/'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/': {
      id: '/_authenticated/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId/': {
      id: '/_authenticated/accounts/$accountId/'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/user-inventory': {
      id: '/_authenticated/sites/$siteId/user-inventory'
      path: '/sites/$siteId/user-inventory'
      fullPath: '/sites/$siteId/user-inventory'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdUserInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/upstream-tasks': {
      id: '/_authenticated/sites/$siteId/upstream-tasks'
      path: '/sites/$siteId/upstream-tasks'
      fullPath: '/sites/$siteId/upstream-tasks'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdUpstreamTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/system-tasks': {
      id: '/_authenticated/sites/$siteId/system-tasks'
      path: '/sites/$siteId/system-tasks'
      fullPath: '/sites/$siteId/system-tasks'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdSystemTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/subscription-plans': {
      id: '/_authenticated/sites/$siteId/subscription-plans'
      path: '/sites/$siteId/subscription-plans'
      fullPath: '/sites/$siteId/subscription-plans'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/status': {
      id: '/_authenticated/sites/$siteId/status'
      path: '/sites/$siteId/status'
      fullPath: '/sites/$siteId/status'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/stats': {
      id: '/_authenticated/sites/$siteId/stats'
      path: '/sites/$siteId/stats'
      fullPath: '/sites/$siteId/stats'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/rankings': {
      id: '/_authenticated/sites/$siteId/rankings'
      path: '/sites/$siteId/rankings'
      fullPath: '/sites/$siteId/rankings'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/pricing-groups': {
      id: '/_authenticated/sites/$siteId/pricing-groups'
      path: '/sites/$siteId/pricing-groups'
      fullPath: '/sites/$siteId/pricing-groups'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPricingGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/performance-history': {
      id: '/_authenticated/sites/$siteId/performance-history'
      path: '/sites/$siteId/performance-history'
      fullPath: '/sites/$siteId/performance-history'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPerformanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/model-catalog': {
      id: '/_authenticated/sites/$siteId/model-catalog'
      path: '/sites/$siteId/model-catalog'
      fullPath: '/sites/$siteId/model-catalog'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdModelCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/logs': {
      id: '/_authenticated/sites/$siteId/logs'
      path: '/sites/$siteId/logs'
      fullPath: '/sites/$siteId/logs'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/financial-operations': {
      id: '/_authenticated/sites/$siteId/financial-operations'
      path: '/sites/$siteId/financial-operations'
      fullPath: '/sites/$siteId/financial-operations'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdFinancialOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/channel-inventory': {
      id: '/_authenticated/sites/$siteId/channel-inventory'
      path: '/sites/$siteId/channel-inventory'
      fullPath: '/sites/$siteId/channel-inventory'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdChannelInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/stats': {
      id: '/_authenticated/customers/$customerId/stats'
      path: '/customers/$customerId/stats'
      fullPath: '/customers/$customerId/stats'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId/stats': {
      id: '/_authenticated/accounts/$accountId/stats'
      path: '/accounts/$accountId/stats'
      fullPath: '/accounts/$accountId/stats'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedStatisticsAccountsRoute: typeof AuthenticatedStatisticsAccountsRoute
  AuthenticatedStatisticsChannelsRoute: typeof AuthenticatedStatisticsChannelsRoute
  AuthenticatedStatisticsCustomersRoute: typeof AuthenticatedStatisticsCustomersRoute
  AuthenticatedStatisticsGlobalRoute: typeof AuthenticatedStatisticsGlobalRoute
  AuthenticatedStatisticsGroupsRoute: typeof AuthenticatedStatisticsGroupsRoute
  AuthenticatedStatisticsModelsRoute: typeof AuthenticatedStatisticsModelsRoute
  AuthenticatedStatisticsNodesRoute: typeof AuthenticatedStatisticsNodesRoute
  AuthenticatedStatisticsSitesRoute: typeof AuthenticatedStatisticsSitesRoute
  AuthenticatedStatisticsTokensRoute: typeof AuthenticatedStatisticsTokensRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedChannelInventoryIndexRoute: typeof AuthenticatedChannelInventoryIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedExportsIndexRoute: typeof AuthenticatedExportsIndexRoute
  AuthenticatedFinancialOperationsIndexRoute: typeof AuthenticatedFinancialOperationsIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedModelCatalogIndexRoute: typeof AuthenticatedModelCatalogIndexRoute
  AuthenticatedPerformanceHistoryIndexRoute: typeof AuthenticatedPerformanceHistoryIndexRoute
  AuthenticatedPricingGroupsIndexRoute: typeof AuthenticatedPricingGroupsIndexRoute
  AuthenticatedRankingsIndexRoute: typeof AuthenticatedRankingsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedSubscriptionPlansIndexRoute: typeof AuthenticatedSubscriptionPlansIndexRoute
  AuthenticatedSystemTasksIndexRoute: typeof AuthenticatedSystemTasksIndexRoute
  AuthenticatedUpstreamTasksIndexRoute: typeof AuthenticatedUpstreamTasksIndexRoute
  AuthenticatedUserInventoryIndexRoute: typeof AuthenticatedUserInventoryIndexRoute
  AuthenticatedAccountsAccountIdStatsRoute: typeof AuthenticatedAccountsAccountIdStatsRoute
  AuthenticatedCustomersCustomerIdStatsRoute: typeof AuthenticatedCustomersCustomerIdStatsRoute
  AuthenticatedSitesSiteIdChannelInventoryRoute: typeof AuthenticatedSitesSiteIdChannelInventoryRoute
  AuthenticatedSitesSiteIdFinancialOperationsRoute: typeof AuthenticatedSitesSiteIdFinancialOperationsRoute
  AuthenticatedSitesSiteIdLogsRoute: typeof AuthenticatedSitesSiteIdLogsRoute
  AuthenticatedSitesSiteIdModelCatalogRoute: typeof AuthenticatedSitesSiteIdModelCatalogRoute
  AuthenticatedSitesSiteIdPerformanceHistoryRoute: typeof AuthenticatedSitesSiteIdPerformanceHistoryRoute
  AuthenticatedSitesSiteIdPricingGroupsRoute: typeof AuthenticatedSitesSiteIdPricingGroupsRoute
  AuthenticatedSitesSiteIdRankingsRoute: typeof AuthenticatedSitesSiteIdRankingsRoute
  AuthenticatedSitesSiteIdStatsRoute: typeof AuthenticatedSitesSiteIdStatsRoute
  AuthenticatedSitesSiteIdStatusRoute: typeof AuthenticatedSitesSiteIdStatusRoute
  AuthenticatedSitesSiteIdSubscriptionPlansRoute: typeof AuthenticatedSitesSiteIdSubscriptionPlansRoute
  AuthenticatedSitesSiteIdSystemTasksRoute: typeof AuthenticatedSitesSiteIdSystemTasksRoute
  AuthenticatedSitesSiteIdUpstreamTasksRoute: typeof AuthenticatedSitesSiteIdUpstreamTasksRoute
  AuthenticatedSitesSiteIdUserInventoryRoute: typeof AuthenticatedSitesSiteIdUserInventoryRoute
  AuthenticatedAccountsAccountIdIndexRoute: typeof AuthenticatedAccountsAccountIdIndexRoute
  AuthenticatedCustomersCustomerIdIndexRoute: typeof AuthenticatedCustomersCustomerIdIndexRoute
  AuthenticatedSitesSiteIdIndexRoute: typeof AuthenticatedSitesSiteIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedStatisticsAccountsRoute: AuthenticatedStatisticsAccountsRoute,
  AuthenticatedStatisticsChannelsRoute: AuthenticatedStatisticsChannelsRoute,
  AuthenticatedStatisticsCustomersRoute: AuthenticatedStatisticsCustomersRoute,
  AuthenticatedStatisticsGlobalRoute: AuthenticatedStatisticsGlobalRoute,
  AuthenticatedStatisticsGroupsRoute: AuthenticatedStatisticsGroupsRoute,
  AuthenticatedStatisticsModelsRoute: AuthenticatedStatisticsModelsRoute,
  AuthenticatedStatisticsNodesRoute: AuthenticatedStatisticsNodesRoute,
  AuthenticatedStatisticsSitesRoute: AuthenticatedStatisticsSitesRoute,
  AuthenticatedStatisticsTokensRoute: AuthenticatedStatisticsTokensRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedChannelInventoryIndexRoute:
    AuthenticatedChannelInventoryIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedExportsIndexRoute: AuthenticatedExportsIndexRoute,
  AuthenticatedFinancialOperationsIndexRoute:
    AuthenticatedFinancialOperationsIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedModelCatalogIndexRoute: AuthenticatedModelCatalogIndexRoute,
  AuthenticatedPerformanceHistoryIndexRoute:
    AuthenticatedPerformanceHistoryIndexRoute,
  AuthenticatedPricingGroupsIndexRoute: AuthenticatedPricingGroupsIndexRoute,
  AuthenticatedRankingsIndexRoute: AuthenticatedRankingsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedSubscriptionPlansIndexRoute:
    AuthenticatedSubscriptionPlansIndexRoute,
  AuthenticatedSystemTasksIndexRoute: AuthenticatedSystemTasksIndexRoute,
  AuthenticatedUpstreamTasksIndexRoute: AuthenticatedUpstreamTasksIndexRoute,
  AuthenticatedUserInventoryIndexRoute: AuthenticatedUserInventoryIndexRoute,
  AuthenticatedAccountsAccountIdStatsRoute:
    AuthenticatedAccountsAccountIdStatsRoute,
  AuthenticatedCustomersCustomerIdStatsRoute:
    AuthenticatedCustomersCustomerIdStatsRoute,
  AuthenticatedSitesSiteIdChannelInventoryRoute:
    AuthenticatedSitesSiteIdChannelInventoryRoute,
  AuthenticatedSitesSiteIdFinancialOperationsRoute:
    AuthenticatedSitesSiteIdFinancialOperationsRoute,
  AuthenticatedSitesSiteIdLogsRoute: AuthenticatedSitesSiteIdLogsRoute,
  AuthenticatedSitesSiteIdModelCatalogRoute:
    AuthenticatedSitesSiteIdModelCatalogRoute,
  AuthenticatedSitesSiteIdPerformanceHistoryRoute:
    AuthenticatedSitesSiteIdPerformanceHistoryRoute,
  AuthenticatedSitesSiteIdPricingGroupsRoute:
    AuthenticatedSitesSiteIdPricingGroupsRoute,
  AuthenticatedSitesSiteIdRankingsRoute: AuthenticatedSitesSiteIdRankingsRoute,
  AuthenticatedSitesSiteIdStatsRoute: AuthenticatedSitesSiteIdStatsRoute,
  AuthenticatedSitesSiteIdStatusRoute: AuthenticatedSitesSiteIdStatusRoute,
  AuthenticatedSitesSiteIdSubscriptionPlansRoute:
    AuthenticatedSitesSiteIdSubscriptionPlansRoute,
  AuthenticatedSitesSiteIdSystemTasksRoute:
    AuthenticatedSitesSiteIdSystemTasksRoute,
  AuthenticatedSitesSiteIdUpstreamTasksRoute:
    AuthenticatedSitesSiteIdUpstreamTasksRoute,
  AuthenticatedSitesSiteIdUserInventoryRoute:
    AuthenticatedSitesSiteIdUserInventoryRoute,
  AuthenticatedAccountsAccountIdIndexRoute:
    AuthenticatedAccountsAccountIdIndexRoute,
  AuthenticatedCustomersCustomerIdIndexRoute:
    AuthenticatedCustomersCustomerIdIndexRoute,
  AuthenticatedSitesSiteIdIndexRoute: AuthenticatedSitesSiteIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
